### PR TITLE
[22091] Ensure selecting the same SVG icon does not cause the icon to disappear

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos I think this should be nested `if ... then`s so that the `close this stack` only happens if the target is the icon list - otherwise the stack will close when another part is clicked on that doesn't handle mouseUp

**Comment by livecodepanos** [comment]
Good catch @livecodeali :) Will push an update now

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cd9736d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cd9736d77050a97e91ea22bc162bcddba48da5c5

**Pull request merged**
