### PR TITLE
[[ Bug 16190 ]] Add revEnvironment functions for extensions and user extensions paths

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Do these need API docs?  I think @mwieder mentioned that some of the other revEnvironment functions have API docs (but I'm not sure if I remember correctly)

**Comment by peter-b** [comment]
@livecodeali Also, can we put this into dp-9?

**Comment by livecodeali** [comment]
I'm not aware of any other IDE docs for revEnvironment... functions, but I could be wrong.

And yes, this can go into DP 9, was just adding a conservative milestone :-)

**Comment by mwieder** [comment]
Not exactly "docs"... they're in the release notes for LC 5, but that's it. Would be nice, though.

**Comment by livecodeali** [comment]
Cool, I will add something to the release notes, and make sure I add these things to my list of IDE stuff to document.

**Comment by peter-b** [comment]
@livecode-vulcan review ok e84a8f1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e84a8f1898d00e2abed8f72baa98c8411d1a7abe

**Pull request merged**
