### PR TITLE
[[ Arrays ]] Use more efficient key iteration syntax

### PR DESCRIPTION
**Pull request by livecodeali**
- Replace occurrences of `is [not] among the lines of
  the keys of <array>` with `is [not] among the keys of
  <array>`
- Replace occurrences of `the number of lines of the
  keys of <array>` with `the number of elements of <array>`

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 661c609

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 661c60917c98d8ec0ac44a4afd63c87c8beba624

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4faccf7

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4faccf7376dbf78c25d2ab02104ba14f6b7353bd

**Pull request merged**
