### PR TITLE
Ensure text descenders on checkbox labels in the PI are not cut off

### PR DESCRIPTION
**Pull request by runrevelanor**
Closes: #1039

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevelanor What was the problem, exactly?

**Comment by runrevelanor** [comment]
The checkbox control in the editor template needed to be made slightly taller.

**Comment by livecodeali** [comment]
@runrevelanor You don't need the change to `com.livecode.pi.boolean.livecode` anymore do you?

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0cedc6a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0cedc6a09079cab8e16521bdece90697ffe8e751

**Pull request merged**
