### PR TITLE
[[ Bug 18920 ]] reenable selection of single char in SE using mouse

### PR DESCRIPTION
**Pull request by BerndN**
single char is not selectable with mouse

### CODE REVIEW

**Comment by livecodepanos** [comment]
Thank you @BerndN. The fix works for me, tested on OSX and Windows. One minor thing though:

Could you please rename the file `notes/Bugfix-18920.md` to `notes/bugfix-18920.md`?

You can do that by `git mv notes/Bugfix-18920.md notes/bugfix-18920.md`
(and then you have to commit and push this change)

**Comment by BerndN** [comment]
@livecodepanos renaming done. Hope this is the last change to this...

**Comment by livecodepanos** [comment]
Thanks @BerndN :)

@livecode-vulcan review ok 479cd82

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 479cd8238d8c8f2735982fe52b790576b8f4b91c

**Pull request merged**
