### PR TITLE
[[ Bug 23193 ]] Add support for App Tracking Transparency

### PR DESCRIPTION
**Pull request by livecodepanos**
This patch adds support for App Tracking Transparency in the standalone builder, by adding a checkbox for adding the required plist key, as well as a field for including the usage description string.

### CODE REVIEW

**Comment by livecodepanos** [comment]
Before:

Screenshot 2021-05-06 at 15 58 16

After:

Screenshot 2021-05-06 at 15 51 12

Screenshot 2021-05-06 at 15 51 29

**Comment by livecodepanos** [comment]
Binary changes:

The script of the checkbox:

```
on mouseUp
   storeSetting "AppTrackingTransparency", the hilite of me
   set the visible of field "App Tracking Transparency Message" to the hilite of me
end mouseUp
```

Script of the field:

```
on closeField
   storeSetting "AppTrackingTransparencyMessage", the text of me
end closeField
```

**Comment by livecodeian** [comment]
> Binary changes:
> 
> The script of the checkbox:
> 
> ```
> on mouseUp
>    storeSetting "AppTrackingTransparency", the hilite of me
>    set the visible of field "App Tracking Transparency Message" to the hilite of me
> end mouseUp
> ```

@livecodepanos I think it would be better here to toggle the enabled of the field, rather than its visibility

**Comment by livecodepanos** [comment]
@livecodeian I have updated the checkbox to do:

```
on mouseUp
   storeSetting "AppTrackingTransparency", the hilite of me
   set the enabled of field "App Tracking Transparency Message" to the hilite of me
end mouseUp
```

**Comment by livecodeian** [comment]
@livecode-vulcan review ok a6d71a5

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeian ok a6d71a58c660b5a09890802efb479c1c8f30e6ec

**Pull request merged**
