### PR TITLE
Display the Front Scripts in the Message Box correctly on first open

### LINKED ISSUE #1116: Front scripts pane displays incorrectly on first open

### PR DESCRIPTION
**Pull request by runrevelanor**
An error was being thrown when setting the palette footer items when
the Front Scripts card as first opened, this prevented the list
being drawn.

Closes #1116

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevelanor Can you post a summary of your binary stack code changes in a comment or gist please?

**Comment by runrevelanor** [comment]
I ended up just retyping the line as I tried to find the cause of the issue, which fixed it. Perhaps there was a rogue non printing character as a result of a copy and paste? The line is the same and in the same place but there is now no error.

The line is

`showFrameItem "removeAll"`

in the preOpenCard handler of the Front Scripts card.

**Comment by livecodeali** [comment]
Fair enough!
@livecode-vulcan review ok 6e77444

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6e7744474555931a6ba62e6a8fe298d9d554e1a6

**Pull request merged**
