### PR TITLE
[[ PI ]] Add editor which is a list of copies of another editor

### PR DESCRIPTION
**Pull request by livecodeali**
This will be able to replace the colorlist editor once I work out the best way of passing 'newline' from LCB as the delimiter in metadata.

### CODE REVIEW

**Comment by runrevben** [comment]
@livecode-vulcan review ok 2745439

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok 274543915bee78e49aaa65875c50218d266da46b

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1ad33e9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1ad33e932072c9dba5d1ae867ab45e1ed2c0b29c

**Pull request merged**
