### PR TITLE
[Bug 14003] Make sure enabling Tools palette from menubar does show revTools stack

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 52775ff

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 52775ff0861a64c9cb2d71f53228d7cd82d4c2f5

**Comment by peter-b** [comment]
@livecodeali @livecodepanos Should this change go into `develop-8.0`?

**Comment by livecodeali** [comment]
It was reported against 6.5.2, so I thought probably not

**Comment by livecodepanos** [comment]
This bug affects LC 8 as well, so I think it should go into develop-8.0 (i.e. into LC 8.0.2-RC1)

**Comment by livecodepanos** [comment]
I am closing this PR and resubmitting it against develop-8.0

**Pull request closed without merging**
