### PR TITLE
[[ Guides ]] updated start center screen shots

### PR DESCRIPTION
**Pull request by asayd**
- Start Center first run 
- Start Center with labels

### CODE REVIEW

**Comment by asayd** [comment]
@livecodeali Hope I did that right.

**Comment by livecodeali** [comment]
@asayd You did indeed, thank you!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 845233d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 845233d8f12389572abc4751606b87890268df5f

**Pull request merged**
