### PR TITLE
[[ Feature ]] S/B Added Build No for iOS Panel

### PR DESCRIPTION
**Pull request by abrisan**

### CODE REVIEW

**Comment by livecodealex** [comment]
screen shot 2017-05-25 at 11 41 53

**Comment by abrisan** [comment]
Added this script for the field
```
on closeField
   storeSetting "bundle build", me
end closeField
```

**Comment by abrisan** [comment]
screen shot 2017-05-25 at 11 47 33

**Comment by abrisan** [comment]
Depends on

https://github.com/livecode/livecode/pull/5514

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok e47365a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok e47365a666b6c635370c5af0d57e6cdd19d3b39c

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 9ba7062

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 9ba706238209677e6f289e8382070d78b1f017b8

**Pull request merged**
