### PR TITLE
Set the initial size and position of the Script Editor to be on screen

### PR DESCRIPTION
**Pull request by runrevelanor**
Calculate a size and position for the initial Script Editor that is
proportional to the working screen rect and fully on screen.

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevelanor Can you add a release note please?

**Comment by GoingLive** [comment]
The problem I have on Windows 10, 64bit, LC 8.0 (dp16) is that the initial location and size of the script editor sometimes is ok starting a new stack, Sometimes I found it far off-screen.opening and closing it.Or it does not show up at all (just disappearing with a visual effect) with still a correct location and visibility = true. I hope it can be fixed for dp 17..Because without script editor no work is really possible.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 13e6c09

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 13e6c09d80642e6ae3e70ebcd269c19ab48c4b36

**Pull request merged**
