### PR TITLE
[[ Bug 19547 ]] Fixed bug preventing the find of |

### PR DESCRIPTION
**Pull request by abrisan**

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @livecodealex, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by runrevmark** [comment]
@livecodealex : Could you check through the PCRE syntax and see if we cover the whole list of operators we might need to escape? http://www.pcre.org/original/doc/html/pcrepattern.html

**Comment by livecode-vulcan** [comment]
📝 Hi @livecodealex, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/CONTRIBUTING.md) for more information.

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 132e147

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 132e147709d5a843287df7e28e7f87cb2bedfcf8

**Pull request merged**
