### PR TITLE
Fix regression to ask and answer dialog locations

### PR DESCRIPTION
**Pull request by montegoulding**
This patch also makes the ask dialog pass strict compilation

### CODE REVIEW

**Comment by livecodeali** [comment]
@montegoulding Could you link to a gist of the script diff please?

**Comment by montegoulding** [comment]
@livecodeali here you go:

https://gist.github.com/montegoulding/ddeab203e6ba25656b03d04bfe753305/revisions

and

https://gist.github.com/montegoulding/52bde6c254faeccf71cf09ce7b801fd6/revisions

**Comment by livecodeali** [comment]
@montegoulding Thanks! Good way of doing it too.

**Comment by livecodeali** [comment]
@montegoulding Looks good, needs a bugfix note though

**Comment by montegoulding** [comment]
I think it's a regression on an existing bug that had a note and was reopened

**Comment by livecodeali** [comment]
Ah I see, sorry.
@livecode-vulcan review ok bf78766

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok bf787661e20036d71756da460c5460f593457206

**Pull request merged**
