### PR TITLE
Improve the multi-line mode of the Message Box

### PR DESCRIPTION
**Pull request by runrevelanor**
- Only allow the separator to resize the 2 panels
- Allow text to be selected and copied from the results field

Change the background color for the pending messages, front and back scripts
and stacks in use to white (issue #992)

### CODE REVIEW

**Comment by runrevelanor** [comment]
Closes: #948 
Closes: #992

**Comment by livecodeali** [comment]
Can you add a `constant kSeparatorSize = 10` or something like that, and replace the 5s with `kSeparatorSize / 2` - that way we can change it easily in one place if it needs changing, and the 5s are less mysterious.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b8396c7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b8396c7b99e00a81396838a608bfe8d680066b9f

**Pull request merged**
