### PR TITLE
[[ IDE Library ]] Add some docs and tests for IDE library API

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
Random question: am I write in thinking that `/** */` will be interpreted as a doc comment (i.e. I don't need two asterisks at the end as well as at the start)?

**Comment by peter-b** [comment]
Second random question: should we have some style guidelines for writing API documentation, at the level of, "The summary should be a brief sentence written in the imperative voice"?

**Comment by peter-b** [comment]
@livecode-vulcan review ok efd5365

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok efd5365b9482db4aef41f6ad9c81f8aa8be9c7fc

**Comment by livecodeali** [comment]
To the first random question, yes you are correct. I just think it's nicer to have them balanced, and so that you can see that the end is supposed to be the end of a docs comment.

To the second, definitely!

**Pull request merged**
