### PR TITLE
[[ IDE ]] Remove extension store infrastructure from IDE

### LINKED ISSUE #638: Remove extension store card from extension manager
Because we're not going to ship the extension store in LiveCode 8.0.0 GM.

### PR DESCRIPTION
**Pull request by livecodeali**
Closes #638
We aren't focusing on distribution of extensions from the store for
8.0 GM anymore, and I think various things about how we do it will
also change (which is why I've decided to delete code rather than
comment it out).

### CODE REVIEW

**Comment by livecodeali** [comment]
Diff: https://gist.github.com/livecodeali/34279ee42cf1935f9c0a

**Comment by peter-b** [comment]
@livecode-vulcan review ok 3d7530b

**Comment by peter-b** [comment]
@livecodeali Um, actually, is this supposed to _remove_ the extension manager palette stack file?

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 3d7530b0015becada25621206312d12b6aea345e

**Comment by livecodeali** [comment]
@peter-b No, The other two cards on the stack show what extensions are installed (widgets and libraries) so is potentially still useful.

**Pull request merged**
