### PR TITLE
Set gRevDevelopment depending on if the engine is in the build dir

### PR DESCRIPTION
**Pull request by montegoulding**
Just an idea to see if people like it.

### CODE REVIEW

**Comment by livecodeali** [comment]
I don't see why not. 
@livecode-vulcan review ok d25d3ec

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok d25d3ecc11ee8f4156befcef12c537fde74f8a82

**Comment by mwieder** [comment]
Yes, please. I end up invoking the message box and doing this at every launch anyway.

**Comment by livecodepanos** [comment]
I have been testing LC 8.0.2 rc1 (from the staging area) and it seems that now setting `grevdevelopment` to `true` has no result, since if I put a breakpoint in e.g. `revSaveAsAndroidStandalone` stack script, in `revSaveAsMobileStandaloneMain` command, the breakpoint is not respected. Moreover, typing `put grevdevelopment` in the msg box returns "grevdevelopment". So it looks like `grevdevelopment` is not treated as a global.

**Comment by montegoulding** [comment]
Thanks @livecodepanos I'll check it out

**Pull request merged**
