### PR TITLE
[[ Bug 16299 ]] Added checkbox to disable ATS on iOS S/B

### PR DESCRIPTION
**Pull request by livecodesebastien**
Xcode 7.0-introduced ATS prevents users to load URL that do not use HTTPS protocol.
That can be circumvented by adding an entry in the Plist file of the app - which can be asked for in the
iOS Standalone Settings (the default behaviour being to comply to Apple strict rules)

### CODE REVIEW

**Comment by livecodesebastien** [comment]
Diff: https://gist.github.com/livecodesebastien/24bfa02abf5f17d4b07a

**Comment by livecodesebastien** [comment]
UI change: screen shot 2015-11-02 at 15 22 05

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 1d476c1

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 1d476c11b200e85160e5be1316b16dc0b45c8519

**Pull request merged**
