### PR TITLE
Force some prefs while gREVDevelopment is true

### PR DESCRIPTION
**Pull request by montegoulding**
- script indent = 3
- explicitVariables = true
- preserveVariables = true
- comment char `--`
- gREVShowStacks = true

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b24d13e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b24d13eef8b41eb54adc439d3dfb9923cdd3dbfa

**Comment by mwieder** [comment]
I missed my chance to comment on this before it got merged (that was fast), but... why set preserveVariables to true? Is there some interaction between that and gRevDevelopment? I have it set false in the IDE preferences. So now gRevDevelopment=true will change that. I don't see a corresponding restoration of these variables when gRevDevelopment is set back to false.

**Comment by montegoulding** [comment]
IDE scripts often store state in script locals. With `preserveVariables` false it breaks the IDE a multitude of unknowable ways.

**Comment by mwieder** [comment]
Interesting. Thanks.

**Comment by jameshale** [comment]
> breaks the IDE a multitude of unknowable ways.

Hmm, if they are unknowable how do you know?

**Comment by montegoulding** [comment]
Exactly @jameshale!

**Comment by mwieder** [comment]
LOL

**Pull request merged**
