### PR TITLE
[[ Tutorial ]] Fixes and enhancements to support BMI app tutorial

### PR DESCRIPTION
**Pull request by livecodeali**
[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/909)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[Toolset/libraries/revideextensionlibrary.livecodescript, line 95 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/909#-KAdWQHh3L-ted02_gew:-KAdUUpSz8EzJayUDumM:1657557474) ([raw file](https://github.com/livecode/livecode-ide/blob/0833a0476a22ee54182ee9a39d9a9224f8a13443/Toolset/libraries/revideextensionlibrary.livecodescript#L95)):_
Very minor stylistic grip: this might be clearer with some `(...)`, for those people like me who can never remember LCS operator precedence.

---

_[Toolset/palettes/menubar/revmenubar.livecodescript, line 869 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/909#-KAdVsSGVC4aGzPATU5t:-KAdVsSGVC4aGzPATU5u:-1914822438) ([raw file](https://github.com/livecode/livecode-ide/blob/0833a0476a22ee54182ee9a39d9a9224f8a13443/Toolset/palettes/menubar/revmenubar.livecodescript#L869)):_
This is some serious black magic that maybe deserves some source comments describing why it's needed and how to regenerate it.

I'm sort of worried about this bitrotting if/when someone updates the menu bar and doesn't update this function accordingly.

---

_[Toolset/palettes/tutorial/revtutorial.livecodescript, line 2312 [r3]](https://reviewable.io:443/reviews/livecode/livecode-ide/909#-KAdeOozSr6vYPJrpQ9A:-KAdeOp-JIsqWR1Ej_kI:-357550406) ([raw file](https://github.com/livecode/livecode-ide/blob/9c2bd0b59b17090e23624bd8ace6834ac74f629e/Toolset/palettes/tutorial/revtutorial.livecodescript#L2312)):_
`if word 1 of pObject is "stack"` maybe?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/909)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/menubar/revmenubar.livecodescript, line 869 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/909#-KAdVsSGVC4aGzPATU5t:-KAdtCKcWT70kXXSzTbr:1695260159) ([raw file](https://github.com/livecode/livecode-ide/blob/0833a0476a22ee54182ee9a39d9a9224f8a13443/Toolset/palettes/menubar/revmenubar.livecodescript#L869)):_
Yes, it's pretty difficult to think of a way round it :-( However, I think it's unlikely that anyone will add to or reorder the top-level menu buttons for a while, so it should be ok from that point of view. You're right though, some sort of warning seems like a good idea

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/909)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/menubar/revmenubar.livecodescript, line 869 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/909#-KAdVsSGVC4aGzPATU5t:-KAdtfQ2IX02yt6vJcz4:-1535010080) ([raw file](https://github.com/livecode/livecode-ide/blob/0833a0476a22ee54182ee9a39d9a9224f8a13443/Toolset/palettes/menubar/revmenubar.livecodescript#L869)):_
On the plus side, the consequences are not dire if this bit-rots - it will just mean the tutorial stack points in the wrong place

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/909)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4f10537

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/909#-:-KAkMwL4VRzW67ZmBwOY:1891419623)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4f10537d30e6d05577c1d5dbf34c3cdd9408c04d

**Pull request merged**
