### PR TITLE
[[ Bug 18475 ]] Fix close combobox bug in font PI

### PR DESCRIPTION
**Pull request by asayd**
Font was not being updated when closing combobox by pressing tab key.

### CODE REVIEW

**Comment by peter-b** [comment]
@asayd Thanks for this patch!  For next time, please write release notes in the imperative mood when possible.  For example:

> Set the **textFont** of a control when tabbing out of the PI textFont editor

@livecode-vulcan review ok 949a409

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 949a4099892371f5161b3536211def7e1ba61f03

**Comment by asayd** [comment]
@peter-b Are you referring to the PR title or the descriptive text?

**Comment by peter-b** [comment]
@asayd I'm referring to the contents of the release note (which I now notice is in the wrong directory).  I like release notes to be positive ("Fix the bug 😃 ") rather than negative ("It is broken 😢" ). I'll make another PR that moves the release note to the correct place.

**Comment by asayd** [comment]
@peter-b Got it. Guidance appreciated, also Re release note in wrong directory.

**Pull request merged**
