### PR TITLE
[[ Guides ]] Update some IDE guides

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevelanor** [comment]
Just a couple of comments.

1. The tools palette screen shot in the "LiveCode Script" guide had an error, the widget section was labelled as buttons. I've attached a new version.

script-build-ui-tools-palette

2. The screenshots of the Script Editor in the "The LIveCode IDE" guide look a little out of date but it hasn't changed much so probably doesn't matter too much.

**Comment by livecodeali** [comment]
@runrevelanor Thanks, I've updated that image of the tools palette, and filed a bug about the script editor images in the IDE guide:http://quality.livecode.com/show_bug.cgi?id=19205

**Comment by runrevelanor** [comment]
@livecode-vulcan review ok 43fa1c3

**Comment by livecode-vulcan** [comment]
💙 review by @runrevelanor ok 43fa1c3ffcf54d88fd8d8056cd89d61f741bda9d

**Pull request merged**
