### PR TITLE
revtemplatechooser is no longer used

### PR DESCRIPTION
**Pull request by mwieder**
The revtemplatechooser.rev stack appears to be an artifact from the revMedia days. It's not referenced from anywhere and the buttons all have code that explicitly does nothing. While it would be nice someday to have this sort of functionality as templates for new users (especially pluggable/maintainable), today the samples seem to serve the same purpose.

### CODE REVIEW

**Comment by montegoulding** [comment]
@mwieder do you think you could `git commit --amend` to prefix the summary line with `[[ Cleanup ]] ` then add an empty line followed by your PR summary message? If you force push after the amend it will update the PR.

**Comment by mwieder** [comment]
Done. Didn't know [[ Cleanup ]] was one of the valid tags. Er... did you want the whole github pr comment as the commit comment?

**Comment by montegoulding** [comment]
Yeah... should be:

```
[[ Cleanup ]] revtemplatechooser is no longer used

The revtemplatechooser.rev stack appears to be an artifact from the revMedia days. It's not 
referenced from anywhere and the buttons all have code that explicitly does nothing. While it 
would be nice someday to have this sort of functionality as templates for new users (especially
pluggable/maintainable), today the samples seem to serve the same purpose.
```

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 31d263c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 31d263c430a86881912d117321b6658f83df697f

**Pull request merged**
