### PR TITLE
[[ PI ]] Add alignment pane to property inspector for multiple objects

### PR DESCRIPTION
**Pull request by livecodeali**
As well as reinstating the alignment pane, this allows custom property 'setters' to be specified in the property definitions, which paves the way for reinstating the geometry manager.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/629)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 11 of 12 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[Toolset/palettes/inspector/editors/com.livecode.pi.align.behavior.livecodescript, line 5 [r3]](https://reviewable.io:443/reviews/livecode/livecode-ide/629#-K2rB8I3GttZ10hNAW-g)** ([raw file](https://github.com/livecode/livecode-ide/blob/035ecef612a9747d9648e3795655a0f55a11f21f/Toolset/palettes/inspector/editors/com.livecode.pi.align.behavior.livecodescript#L5)):</sup>
Why is the `editorMinWidth` of this editor 60, but the other editors all have `editorMinWidth = 0`?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/629)

**Comment by livecodeali** [comment]
<sup>**[Toolset/palettes/inspector/editors/com.livecode.pi.align.behavior.livecodescript, line 5 [r3]](https://reviewable.io:443/reviews/livecode/livecode-ide/629#-K2rB8I3GttZ10hNAW-g)** ([raw file](https://github.com/livecode/livecode-ide/blob/035ecef612a9747d9648e3795655a0f55a11f21f/Toolset/palettes/inspector/editors/com.livecode.pi.align.behavior.livecodescript#L5)):</sup>
There's currently a bug when multiple editors are in one group - if the minwidth is not set for the first one then the second one can overlap it.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/629)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6b10134



---

Reviewed 1 of 12 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/629)

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6b10134fad4dd81e850fbfa0d38643b220d7d488

**Pull request merged**
