### PR TITLE
[[ PB ]] Improve interaction between PB and user stacks

### PR DESCRIPTION
**Pull request by livecodeali**
This patch 
- adds a contextual menu item to objects to navigate to them in the project browser
- adds a dotted line round each control in the pb that corresponds to a currently selected object 

The change to revCore is an addition to the data view behavior which now does

`dispatch "DataViewUpdated" to me` 

when the data view updates (due to scrolling / data change)

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 47e6716

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 47e671650185f4595cb07cc323728968d457c736

**Comment by peter-b** [comment]
@livecode-vulcan review ok 56e4cc1

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 56e4cc11fadfdc53e426388afe34d81f9de4f649

**Pull request merged**
