### PR TITLE
Merge develop 8.2 03.08.17

### PR DESCRIPTION
**Pull request by livecodeali**
Conflict:
in revpreferencesgui - reimplemented the changes described in https://github.com/livecode/livecode-ide/pull/1699

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 95b1e4e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 95b1e4ef1ea206b804e0f634ed81ff069296eb6c

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 563e9af

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 563e9afcdfab64a505f636f6d64927ef7aa5df17

**Pull request merged**
