### PR TITLE
Import images directly, automatically setting the repeatCount

### PR DESCRIPTION
**Pull request by runrevelanor**
When imorting images using the File menu images will be imported
using the import paint from file command. This automatically sets
the repeatCount property of the new image.

Closes: #1026

### CODE REVIEW

**Comment by peter-b** [comment]
@runrevelanor In order to avoid this problem recurring in the future, it might be a good idea to add some comments to the code that explain that that's the reason `import paint` is used here.  What do you think?

**Comment by runrevelanor** [comment]
I can do, it is how it was always done before 8 so is not really a change. If this seems like a good place to add a comment I'll add to the revIDELibrary handler that imports controls.

**Comment by peter-b** [comment]
Sounds good to me.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 001dbae

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 001dbae900e75a9228b097db2e2ab2b102cd47eb

**Pull request merged**
