### PR TITLE
[[ Bug 15854 ]] Set the defaultStack before executing the "stop editing" command

### PR DESCRIPTION
**Pull request by techstrategies**
Bug report submitted:  http://quality.runrev.com/show_bug.cgi?id=15854

### CODE REVIEW

**Comment by livecode-vulcan** [comment]
📝 Hi @techstrategies, I haven't been able to verify that you've signed our [LiveCode Contributor's Agreement](https://livecode.com/account/developer/contribute).

If you have previously signed the Contributor's Agreement, I may not be able to detect it because you haven't [linked your GitHub account to your LiveCode account](https://livecode.com/account/developer/github).

Please see the [information for contributors](https://github.com/runrev/livecode/blob/develop/HACKING.md) for more information.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0003f61

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0003f614e2d4af502d06fb95e18676bc662cc4bc

**Comment by livecodeali** [comment]
Hi @techstrategies, one other thing we require with bug fixes is an additional file called
`bugfix-<bug number>.md`
in the notes directory, which contains a one-line description of the bug fixed in the form
`# <bug description>`

Could you add this file to the pull request please?

**Comment by techstrategies** [comment]
Just added the release notes.
Charles

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 1e8ac01

**Comment by livecodeali** [comment]
Thanks!

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 1e8ac0145fcba85c4fa2c1f103af3ebb172a6a21

**Pull request merged**
