### PR TITLE
[[ IDE Docs API ]] Add a limited docs api, and use in the docs tab of the script editor

### PR DESCRIPTION
**Pull request by livecodeali**
Requires https://github.com/livecode/livecode/pull/3305

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/671)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, 3 of 3 files at r5, 2 of 3 files at r6, 1 of 2 files at r8.
Review status: 8 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[Toolset/libraries/revidedocumentationlibrary.livecodescript, line 66 [r11]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tYSnNlFJ3RuwWYyxT:-K3tYSnNlFJ3RuwWYyxU:1369353579) ([raw file](https://github.com/livecode/livecode-ide/blob/2e7d7d11a5d9e59fe2edd36ca8b3909171ed3ce5/Toolset/libraries/revidedocumentationlibrary.livecodescript#L66)):_
Why does this query need to get  retried? I'm surprised that the database connection would get closed in between the first query in this handler and this query. 

---

_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 28 [r4]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tVc2gG3n_zwzIhOgo:-K3tVc2gG3n_zwzIhOgp:1141798974) ([raw file](https://github.com/livecode/livecode-ide/blob/cd7e026aea9f5339337e2e656a673ba9f16e527d/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L28)):_
Is this a bug in `create in me` or is it expected behaviour?

---

_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 186 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tXCAvvn9J_7DO0vG2:-K3tXCAvvn9J_7DO0vG3:-701118193) ([raw file](https://github.com/livecode/livecode-ide/blob/40cd559d88aedd874cba4d3fb6147923015ad106/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L186)):_
Does this need to know about HTML5?

What happens in the default case?

---

_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 219 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tXNkRZqDEfwZSgdEm:-K3tXNkRZqDEfwZSgdEn:618013318) ([raw file](https://github.com/livecode/livecode-ide/blob/40cd559d88aedd874cba4d3fb6147923015ad106/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L219)):_
The empty paragraph `<p/>` is to add vertical whitespace, right?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671)_

**Comment by livecodeali** [comment]
_[Toolset/libraries/revidedocumentationlibrary.livecodescript, line 66 [r11]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tYSnNlFJ3RuwWYyxT:-K3uKwwGYO5V1QyN7JjC:456271219) ([raw file](https://github.com/livecode/livecode-ide/blob/2e7d7d11a5d9e59fe2edd36ca8b3909171ed3ce5/Toolset/libraries/revidedocumentationlibrary.livecodescript#L66)):_
Heh, oops - left over from a previous iteration. Thanks.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 28 [r4]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tVc2gG3n_zwzIhOgo:-K3uLRfxJ4HAMUUvJmLX:1938291092) ([raw file](https://github.com/livecode/livecode-ide/blob/cd7e026aea9f5339337e2e656a673ba9f16e527d/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L28)):_
Good question - this is one of those pieces of code copied over from the unscriptified version in a script editor object. But it does sound like a bug if it doesn't work.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 186 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tXCAvvn9J_7DO0vG2:-K3uLuLl1M6gW23LZTjZ:277061817) ([raw file](https://github.com/livecode/livecode-ide/blob/40cd559d88aedd874cba4d3fb6147923015ad106/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L186)):_
See above... yes, this probably should know about HTML5, although it doesn't look like html5 has been added to the OS field for any docs entries yet... that could be a fun task.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 186 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tXCAvvn9J_7DO0vG2:-K3uMa1m4f3bjC7YIb2O:-1074466162) ([raw file](https://github.com/livecode/livecode-ide/blob/40cd559d88aedd874cba4d3fb6147923015ad106/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L186)):_
I'm not sure what should happen in the default case. Probably another `ideThrow` sort of situation. for now I'll change the code so that it returns empty, and then just not render anything for that platform if it returns empty.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript, line 219 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-K3tXNkRZqDEfwZSgdEm:-K3uMxafbD1nyWEaKsb1:160394146) ([raw file](https://github.com/livecode/livecode-ide/blob/40cd559d88aedd874cba4d3fb6147923015ad106/Toolset/palettes/script editor/behaviors/revsedocumentationpanebehavior.livecodescript#L219)):_
Yes

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 27706e8

---

Reviewed 2 of 2 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/671#-:-K48OG0C5pIPPCKf_uJS:-336110517)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 27706e8c3babb8d5b9a55606dd99258b10c78e13

**Pull request merged**
