### PR TITLE
[[ PI ]] Allow widget metadata to include built-in properties in inspector

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 6480d4e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6480d4e8f264420abd67800e221984c56e705f11

**Comment by livecodeali** [comment]
Sorry, my bad - totally messes up general widget properties!
@livecode-vulcan review not ok 6480d4e

**Comment by livecode-vulcan** [comment]
💔 review by @livecodeali not ok 6480d4e8f264420abd67800e221984c56e705f11

**Comment by peter-b** [comment]
@livecode-vulcan review ok 5f65394

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 5f65394ac8b1befcc1f025b050167df34de823f3

**Pull request merged**
