### PR TITLE
[[ Bug 18032 ]] Add test

### PR DESCRIPTION
**Pull request by montegoulding**
This test should fail until this [PR](https://github.com/livecode/livecode/pull/4374) is merged

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 6fd71a2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 6fd71a255d43919cf336c9520c098c7f1570f8d5

**Comment by montegoulding** [comment]
This should probably go to WIP status also I guess

**Comment by montegoulding** [comment]
@livecode-vulcan review not ok 6fd71a2

**Comment by livecode-vulcan** [comment]
💔 review by @montegoulding not ok 6fd71a255d43919cf336c9520c098c7f1570f8d5

**Pull request closed without merging**
