### PR TITLE
[Bug 14465] Make sure rulers stay fixed to the stack when moving stack

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
Hi @runrevpanos, the last bit of your patch (removal of incorrect reference to revLibrary stack) is fixed in this PR:
https://github.com/runrev/livecode-ide/pull/395/files

Could you remove that part of the patch so that we don't have a conflict?

**Comment by livecodepanos** [comment]
@livecodeali Sure, I'll update the PR asap

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 151c455

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 151c4559571171241e4c38bc8d125f5c3a987bd2

**Pull request merged**
