### PR TITLE
[[ Docs ]] Add docs editing helper stack to repo

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by montegoulding** [comment]
has this changed since the conference? If not then I'll review it without pulling the patch.

**Comment by livecodeali** [comment]
Nope, no change

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 2a68edb

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 2a68edba14b7a471ab8babe8d0e4c3b921a3a5fa

**Pull request merged**
