### PR TITLE
[[ SB Testing ]] Add S/B tests

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review not ok 5d5c270

**Comment by livecode-vulcan** [comment]
💔 review by @livecodeali not ok 5d5c2705f87530b543c935582c6089af50c84ee2

**Comment by livecodeali** [comment]
These tests pass locally but not on Travis.

**Comment by livecodeali** [comment]
These tests now pass on Travis.

**Comment by peter-b** [comment]
@livecodeali Yay!

@livecode-vulcan review ok 665e290

**Comment by peter-b** [comment]
@livecodeali Do you think it's viable to put these tests into the `develop-8.1` branch?

**Comment by livecodeali** [comment]
@peter-b Possibly - I'll do a test PR. I wondered if maybe the Travis changes that are in develop might be important.

**Comment by livecodeali** [comment]
https://github.com/livecode/livecode-ide/pull/1473

**Pull request closed without merging**
