### PR TITLE
[NO MERGE] Prevent crash in BMI Tutorial

### PR DESCRIPTION
**Pull request by livecodepanos**
This is a workaround that prevents the crash described in report http://quality.livecode.com/show_bug.cgi?id=19837

We still need a proper fix that will address the crash in the engine, though.

Moreover, this patch ensures the vars used in the various scripts are declared first, to prevent an error when in strict compilation mode

### CODE REVIEW

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 8f03aed

**Comment by runrevmark** [comment]
@livecode-vulcan review ok edb9b9b

**Comment by runrevmark** [comment]
@livecode-vulcan review ok edb8b9b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok edb8b9b0fe22b754141646f19fc4bdcf014b9dcc

**Comment by livecodepanos** [comment]
Setting this to [NO MERGE] in case we find a solution that fixes the bug in the engine until Monday. If not, then this PR should be merged.

**Comment by livecodepanos** [comment]
This PR https://github.com/livecode/livecode/pull/5585 fixes the crashes properly, so I am closing this PR. I will create a new PR that addresses the undeclared vars issue

**Pull request closed without merging**
