### PR TITLE
Merge develop 8.2 20.09.17

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
https://gist.github.com/livecodeali/9a2d9cb89d65de073bcb2b6f7ebdde4e

**Comment by livecodeali** [comment]
revsecommoneditorbehavior - The selectionUpdateRequest  is now handled in textReplace (https://github.com/livecode/livecode-ide/pull/1748)
_testrunner - runLoadLibrary is handled in the behavior.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 58c6889

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 58c6889712414591df43f20160b058f363fb4fa8

**Pull request merged**
