### PR TITLE
[[ Tests ]] Remove errant whitespace

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by BerndN** [comment]
@montegoulding sorry about that

**Comment by montegoulding** [comment]
No problem... It's just a side effect of us having a separate IDE repo so the tests don't get run until we merge up

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b17ee02

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b17ee0262fdb8d9ca942ea8881a5b00bf08a15bd

**Pull request merged**
