### PR TITLE
[[ Tests ]] Move TestRunnerRunPrintSummary to tester lib

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 01fa2b4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 01fa2b4687a4dd256d59a39d65b99ade8c31da5d

**Comment by montegoulding** [comment]
It would be good if we had a `don't merge yet` label or something

**Comment by montegoulding** [comment]
@livecodeali should I merge this & update the pointer so the tests pass

**Comment by livecodeali** [comment]
yep!

**Pull request merged**
