### PR TITLE
[[ Module Lcext ]] Update docs for static linking on iOS

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 51ee31d

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 51ee31da9d47c86ac8c384f10b01408fd5175c43

**Comment by livecodeali** [comment]
@livecode-vulcan review ok bba34ef

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok bba34ef2ab82fc46f9b26953d28f96c35458d0a5

**Pull request merged**
