### PR TITLE
[Bug 17586] Make custom props "value" field scrollable in the PI

### PR DESCRIPTION
**Pull request by livecodepanos**
Changes: 

set the `vScrollBar` of fld "value" of grp "template" of card id 1002 of stack "com.livecode.pi.customprops" to true

### CODE REVIEW

**Comment by peter-b** [comment]
I assume this is actually bug 17586 not bug 17856?

**Comment by livecodepanos** [comment]
Argg not the first time I do this mistake!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok abe5e94

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok abe5e9469e746297471d0b6ac602934ba1bf906c

**Pull request merged**
