### PR TITLE
Merge develop 8.1 10.02.17

### PR DESCRIPTION
**Pull request by livecodeali**
Conflict in the IDE test runner which was refactored in develop. A test that the IDE loads correctly was added in develop-8.1. Resolved conflict by adding the IDE test into the develop test runner.

### CODE REVIEW

**Comment by livecodeali** [comment]
For safety, I've made a test PR for this: https://github.com/livecode/livecode/pull/5177

**Comment by livecodeali** [comment]
OK, after a lot of wrangling, test PR passes.

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 0bc3079

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 0bc307952bd12761dbd684a552ec92f64520191b

**Pull request merged**
