### PR TITLE
[[ Bug ]] Remove existing hack for builtin modules and replace with hard-coded list

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevben** [comment]
Would it be possible to do this as metadata in the extension itself? The would save us having to update this list?

**Comment by livecodeali** [comment]
Unfortunately not - the built in modules don't have manifests or anything. I think there should be a better solution to this, but for now replacing a silly hack with a sensible hack seems like the best option.

**Comment by runrevben** [comment]
OK, it's certainly better with the change you've made.

**Comment by runrevben** [comment]
@livecode-vulcan review ok 063b9b4

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok 063b9b4e1c86513679a2aaf28835f93bafd2c649

**Pull request merged**
