### PR TITLE
[[ Dictionary ]] Miscellaneous dictionary formatting fixes

### PR DESCRIPTION
**Pull request by livecodeali**
- Allow changes and param descriptions to be markdown
- Reinstate spaces in references

### CODE REVIEW

**Comment by livecodeali** [comment]
Example for the array params fix: 

```
portNumber(array): The TCP port number on which to accept connections.
{
    key (integer): blah 
    value (array): another array
    {
        key (string) : string
        value (integer): the value
    }
    "portName":
    portName (string): The name of the port 
}
```

->
screen shot 2016-07-11 at 11 38 43

**Comment by livecodeali** [comment]
Requires https://github.com/livecode/livecode/pull/4264

**Comment by peter-b** [comment]
@livecode-vulcan review ok 8118ef2

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 8118ef2f2f710ecab47ed6e48b4b6411ccb75d18

**Pull request merged**
