### PR TITLE
[Bug 13588] Make sure the insertion point is correct when opening the script editor

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
You don't need to do anything with the item delimiter here as its value is local to the handler and defaults to comma

**Comment by livecodepanos** [comment]
Thanks @livecodeali. Btw I actually used the fix itself to update this PR: `edit the script of stack revfrontscriptlibrary at 213,2`    :)

**Comment by livecodeali** [comment]
Nice :-)
@livecode-vulcan review ok fb54834

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fb54834fb169811b4976e75a6e2d3eced654a741

**Pull request merged**
