### PR TITLE
[PI] Update navbar property inspector to reflect navbar changes

### PR DESCRIPTION
**Pull request by peter-b**
- Use **dataChanged** signal instead of **navDataChanged** (to
  match the treeview)
- Rename **navData** property to **itemArray**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 55cfa8b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 55cfa8b09512a7bb903812036412c7cc3a903745

**Comment by peter-b** [comment]
@livecodeali I had to rebase this -- could you please re-review?

**Comment by peter-b** [comment]
Self reviewing since the rebase didn't cause any changes.

@livecode-vulcan review by @livecodeali ok a0f969c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a0f969ca4cbb875135356da12661a25669b14fb6

**Pull request merged**
