### PR TITLE
[[ Scriptify ]] Scriptify datagrid behaviors

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
Depends on https://github.com/livecode/livecode/pull/5973 for standalone builder support

**Comment by montegoulding** [comment]
I have rebased on 8.2 even though we don't really need it here just so we avoid merge conflicts on the binary stack if there's any maintenance to do

**Comment by livecodeali** [comment]
@livecode-vulcan review ok eb11a50

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok eb11a50b4c57ece4903caf7e5020c1417b8f9f1f

**Pull request merged**
