### PR TITLE
[[ Tree View ]] Update color properties of IDE tree views

### PR DESCRIPTION
**Pull request by livecodeali**
They have been set to the IDE default values.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok f9f6892

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f9f68926400ee6d2f36b539987dc718df35335ad

**Comment by livecodeali** [comment]
@peter-b Additional IDE changes needed :-)

**Comment by peter-b** [comment]
LGTM!

@livecode-vulcan review ok 0fba0a0

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 0fba0a0147e38d8c3381fc0e7d286939e10d7ab6

**Pull request merged**
