### PR TITLE
[[ CodeResources ]] Load code resources from extension

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
Depends on https://github.com/livecode/livecode/pull/6180

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f66afae

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f66afaebdce3a3a174b2bc1056b69791f0c6d490

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0c464b2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0c464b221d43ef6dfbb3fb3158e0f50c26ecc431

**Pull request merged**
