### PR TITLE
[[ Tutorials ]] Make tutorials work again

### PR DESCRIPTION
**Pull request by livecodeali**
The tutorial stack had become a bit stale due to IDE code turnover.

This also updates the clock app tutorial so that it completely works.

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/885)

### CODE REVIEW

**Comment by peter-b** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, 1 of 1 files at r12, 1 of 1 files at r13.
Review status: 6 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

_[Toolset/libraries/revidelibrary.8.livecodescript, line 8736 [r9]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAQYoLRvATKJh1e9Zu:-KAAQYoMiuQ36vcGj2BB:460108103) ([raw file](https://github.com/livecode/livecode-ide/blob/0f221d1d1875fb41acf1168559c3786c8bef7e45/Toolset/libraries/revidelibrary.8.livecodescript#L8736)):_
Can this line just be removed?

---

_[Toolset/palettes/menubar/revmenubar.livecodescript, line 828 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAQClQYeG9tJEOozoA:-KAAQClQYeG9tJEOozoB:2040685266) ([raw file](https://github.com/livecode/livecode-ide/blob/01406b4ecae72a895211c70a932015131b8b94e8/Toolset/palettes/menubar/revmenubar.livecodescript#L828)):_
This change doesn't seem to be related to the patch. What does it do?

---

_[Toolset/palettes/tutorial/courses/Getting Started/tutorials/1. Clock App/lessons/1. User interface.txt, line 9 [r14]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAATYEcnuz8GUBu1Gcv:-KAATYEcnuz8GUBu1Gcw:66349327) ([raw file](https://github.com/livecode/livecode-ide/blob/b35fa115a344ce5147c7cd935658566d8c8c9014/Toolset/palettes/tutorial/courses/Getting Started/tutorials/1. Clock App/lessons/1. User interface.txt#L9)):_
Some of the steps have names in "Title Case", and some of them have names "Not in title case".

Some of the step body descriptions don't have full stops.

When the user should type some text literally, would it help to put it in inverted commas `"..."`, or would that risk them typing the punctuation?

---

_[Toolset/palettes/tutorial/courses/Getting Started/tutorials/1. Clock App/lessons/1. User interface.txt, line 25 [r14]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAATFJgIrug3HhPCG8Z:-KAATFJhE-PfIN9R1QBJ:101659500) ([raw file](https://github.com/livecode/livecode-ide/blob/b35fa115a344ce5147c7cd935658566d8c8c9014/Toolset/palettes/tutorial/courses/Getting Started/tutorials/1. Clock App/lessons/1. User interface.txt#L25)):_
What about:

> Setting the background color of the stack will affect all the cards in the stack

---

_[Toolset/palettes/tutorial/courses/Getting Started/tutorials/1. Clock App/lessons/1. User interface.txt, line 385 [r14]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAT1XPFeVnvh7-sQgy:-KAAT1XPFeVnvh7-sQgz:1821041163) ([raw file](https://github.com/livecode/livecode-ide/blob/b35fa115a344ce5147c7cd935658566d8c8c9014/Toolset/palettes/tutorial/courses/Getting Started/tutorials/1. Clock App/lessons/1. User interface.txt#L385)):_
Text file appears to have some weird characters appended to it

---

_[Toolset/palettes/tutorial/revtutorial.livecodescript, line 1841 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAKJh79cu_TAJKS4tK:-KAAKJh79cu_TAJKS4tL:-1614870544) ([raw file](https://github.com/livecode/livecode-ide/blob/74226bafe0e819ec06919ba091e51ea9552da0a8/Toolset/palettes/tutorial/revtutorial.livecodescript#L1841)):_
Out of curiosity, why do you need to wait for 1 ms here?

---

_[Toolset/palettes/tutorial/revtutorial.livecodescript, line 425 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAPwmiyTsTxrtEIbrg:-KAAPwmjgFtHROHrXwwq:-965267737) ([raw file](https://github.com/livecode/livecode-ide/blob/01406b4ecae72a895211c70a932015131b8b94e8/Toolset/palettes/tutorial/revtutorial.livecodescript#L425)):_
We need a feature request for `reverse array _` syntax in LCS. :wink: 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/885)_

**Comment by livecodeali** [comment]
_[Toolset/libraries/revidelibrary.8.livecodescript, line 8736 [r9]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAQYoLRvATKJh1e9Zu:-KAAXKikpFLDXs_x5pf5:677251263) ([raw file](https://github.com/livecode/livecode-ide/blob/0f221d1d1875fb41acf1168559c3786c8bef7e45/Toolset/libraries/revidelibrary.8.livecodescript#L8736)):_
Yes!

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/885)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/menubar/revmenubar.livecodescript, line 828 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAQClQYeG9tJEOozoA:-KAAY1YcvnyHYfYFri-D:-1424394834) ([raw file](https://github.com/livecode/livecode-ide/blob/01406b4ecae72a895211c70a932015131b8b94e8/Toolset/palettes/menubar/revmenubar.livecodescript#L828)):_
Ah thats a 'TODO' - I'm yet to work out what the best way is of finding the display position of the Mac menubar :-/

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/885)_

**Comment by livecodeali** [comment]
_[Toolset/palettes/tutorial/revtutorial.livecodescript, line 1841 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-KAAKJh79cu_TAJKS4tK:-KAAZmQGJxafWOZfDLEP:-884383489) ([raw file](https://github.com/livecode/livecode-ide/blob/74226bafe0e819ec06919ba091e51ea9552da0a8/Toolset/palettes/tutorial/revtutorial.livecodescript#L1841)):_
It was an attempt to fix a glitch where the tutorial stack reappears before the inspector is ready. I will remove.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/885)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 57e9769

---

Reviewed 1 of 1 files at r11, 1 of 1 files at r15, 55 of 55 files at r16, 1 of 1 files at r17, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/885#-:-KAAhPotpFmXTou6meMl:-1925817180)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 57e976909cb216deb3cb4565464ef2ae77b85025

**Pull request merged**
