### PR TITLE
[Bugfix 18987] Reinstate fixedLineHeight for tableField

### PR DESCRIPTION
**Pull request by BerndN**
the input field needs fixedLineHeight for syncing to tableField

### CODE REVIEW

**Comment by livecodepanos** [comment]
Thank you @BerndN. 

The PR is fine. Just one last thing though:
Could you please rename the file `notes/Bugfix-18987.md` to `notes/bugfix-18987.md`?

You can do that by `git mv notes/Bugfix-18987.md notes/bugfix-18987.md`
(and then you have to commit and push this change)

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 4d943d7

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 4d943d7a327858064cfa1ba6c62ec011aaf49f94

**Comment by BerndN** [comment]
@livecodepanos Thank you.

**Pull request merged**
