### PR TITLE
Unsubscribe on closestack

### PR DESCRIPTION
**Pull request by mwieder**
Following on the heels of fixing the subscribe/unsubscribe mechanism for the tools palette, here are similar fixes for three other stacks.

### CODE REVIEW

**Comment by livecodeali** [comment]
@mwieder Similarly, some extra files here.

**Comment by livecodeali** [comment]
@mwieder Actually tools, message box, extension builder, extension manager, inspector and dictionary all use the palette behavior, so the unsubscribe all there fixes this for all of those. So if you could remove those extra files and the change to the message box behavior, then this will cover all those situations and supercede https://github.com/livecode/livecode-ide/pull/741.

**Comment by mwieder** [comment]
Cool. Inheritance is wonderful. Changes pushed.

**Comment by mwieder** [comment]
I did a hard reset and pushed, so I think 742 should be good now.

**Comment by livecodeali** [comment]
Thanks Mark!
@livecode-vulcan review ok 771f66a

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 771f66a6e31c1a42ea88ac369e08c56b5f487f2a

**Pull request merged**
