### PR TITLE
[Bug 15918] Allow newly created buttons to appear offscreen

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodestephen** [comment]
Is this the same as http://quality.runrev.com/show_bug.cgi?id=13826

**Comment by livecodepanos** [comment]
Hi @livecodestephen, thanks for spotting this. Yes, the cause is the same. I'll apply a similar fix to newImage handler to address bug 13826. Btw it seems that newField, newPlayer, newGraphic, newScrollbar follow the same pattern.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8e7e304

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8e7e3043e4e8786eaddbfac29254c8c5596c3c4e

**Pull request merged**
