### PR TITLE
[[ Bug 7303 ]] Cherry-picked auto-complete on develop-8.1

### PR DESCRIPTION
**Pull request by montegoulding**
I will leave PR #1700 open while we work out which version autocomplete should go in. This patch should be everything required for autocomplete and bracket completion.

### CODE REVIEW

**Comment by livecodeali** [comment]
This is definitely good enough to go as far as I can see - hopefully any minor issues can be ironed out in the release process (although I don't see any yet)
@livecode-vulcan review ok 677c401

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 677c4013ca1854b282aa506a87b048d61a68de6d

**Comment by livecodeali** [comment]
(obviously this shouldn't be merged before https://github.com/livecode/livecode/pull/5746)

**Comment by montegoulding** [comment]
@livecodeali I've found a couple of things I'd like to tweak while using this today

- I often type something quickly then hit tab to format the handler and this is catching the autocomplete and messing up what I typed which is rather annoying (haven't looked into this yet)
- The left and right arrow key handling appears to be both unnecessary and it occasionally breaks moving the cursor so that needs to be removed

**Comment by montegoulding** [comment]
@livecodeali I think I've sorted out the above issues and the issue where occasionally the completions weren't showing up

**Comment by livecodeali** [comment]
@livecode-vulcan review ok cdaad06

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok cdaad065869682bc7b373ea2a17af5df106b7a44

**Pull request merged**
