### PR TITLE
[[ Standalone Settings ]] Improve usability of extensions inclusion section

### PR DESCRIPTION
**Pull request by livecodeali**
Diff: https://gist.github.com/livecodeali/da3cc7cb9aabe083df8b
screen shot 2015-10-30 at 09 57 27

### CODE REVIEW

**Comment by peter-b** [comment]
This fixes [bug 16266](http://quality.runrev.com/show_bug.cgi?id=16266).

It looks like a massive improvement in usability!

@livecode-vulcan review ok bf57ad4

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok bf57ad4ff2d958680a1e2053d76f6b365cf1980f

**Comment by livecodeali** [comment]
@livecode-vulcan review by @peter-b ok 306fcb9

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 306fcb9d8a4e1b17c98a1cf1fb482e211a999e69

**Pull request merged**
