### PR TITLE
Support for loading script libraries from extensions directory

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 62b1db4

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 62b1db49cfe8669b78d440d5938cd6b257a11bcb

**Comment by montegoulding** [comment]
@livecodeali that was quick ;-) I was just about to comment on this saying it might be good to (perhaps additionally) look in Extensions/com.livecode.script-library.\* for the libray when installed.

**Comment by livecodeali** [comment]
Hmm presumably everything there should be loaded at startup though

**Comment by livecodeali** [comment]
I'm not sure.

**Comment by montegoulding** [comment]
OK, I'll leave as is and we can look into that later

**Pull request merged**
