### PR TITLE
Merge release 8.1.1 18.10.2016

### PR DESCRIPTION
**Pull request by livecodepanos**
Conflict in `revstandalonesettings.8.rev`, because of this patch https://github.com/livecode/livecode-ide/pull/1424.

Resolved by keeping the `develop-8.1` version of this file, meaning that this patch is NOT present. I will submit a separate PR against `develop-8.1` for this

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodepanos Could you please push the patch that re-implements PR #1424 on `develop-8.1` onto _this_ branch? That will keep everything related to the merge up in one place. Thank you!

**Comment by livecodepanos** [comment]
@peter-b Done :)

**Comment by peter-b** [comment]
@livecode-vulcan review ok 74c2fcb

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 74c2fcbfd32c6d441b2b9588c5f54cbc6a5d3af8

**Pull request merged**
