### PR TITLE
[[ Tutorial ]] Use smaller images in To Do List tutorial

### PR DESCRIPTION
**Pull request by livecodeali**
- Add mechanism to include smaller version of images if they are too tall for a smaller screen
- Add smaller versions of To Do List images

### CODE REVIEW

**Comment by runrevmark** [comment]
Would it be possible to make 'small' image generation automatic - i.e. by downsizing the normal size images if a certain screen size criteria is not met?

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 5790c72

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 5790c72b6042fa6ec9f83b5edf2b40dd1174aea9

**Comment by livecodeali** [comment]
That might make more sense, although then you have to add logic for the given image whether it actually needs resizing for smaller screens or not. On balance probably better than adding more images to the repo

**Comment by runrevmark** [comment]
I've added http://quality.livecode.com/show_bug.cgi?id=20101 to track this.

@livecode-vulcan review ok 5790c72

**Pull request merged**
