### PR TITLE
Merge develop 8.1 09.01.17

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8e0506f
Clean merge

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8e0506fa6dd45c6cbf02174016e6e783bf9d0f98

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok e6c2ae1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok e6c2ae1b096b3c718e6bdbeda2feddb69b4042b7

**Pull request merged**
