### PR TITLE
[[ Bug 19856 ]] Don't subscribe to ideExtensionLog from card and stack

### PR DESCRIPTION
**Pull request by livecodeali**
Remove re-subscription to ideExtensionLog when selecting a new extension from the dropdown menu - this was causing subscription by the stack in addition to previous subscription by the card.

### CODE REVIEW

**Comment by livecodeali** [comment]
Removed:
```
revIDEUnsubscribeAll
revIDESubscribe "ideExtensionLog"
```
from script of openExtension handler

**Comment by livecodeali** [comment]
Also added to script of stack:
```
on closeStack
   revIDEUnsubscribeAll
end closeStack
```

**Comment by runrevmark** [comment]
@livecode-vulcan review ok b7f181e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok b7f181e061862f71ce615edae21ca4d9eb4c7729

**Pull request merged**
