### PR TITLE
[[ Bug 19359, 19357 ]] Remote debugger issues

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@montegoulding could you add a bugfix note for 19359? (There is already one for 19357)

**Comment by montegoulding** [comment]
hmm... yeah I thought I'd added it to a private PR @livecodepanos but perhaps I just intended to. Either way it's more appropriate here given the change is here.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 0418da1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 0418da17660d33b5537d5b9b1ff6788f85c1388d

**Pull request merged**
