### PR TITLE
docs: Refine LiveCode 8 release notes

### PR DESCRIPTION
**Pull request by peter-b**
Tweak and reorganise IDE release notes to match changes made in livecode/livecode#3410.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b7ea667

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b7ea667362ef2e2b1cbe9fab0e2a08445df85b8d

**Comment by peter-b** [comment]
@livecodeali I've updated the pull request, fixing the merge conflict.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 01d2ccb

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 01d2ccbc0dd25a554ef2182f09062c1119b3f301

**Pull request merged**
