### PR TITLE
[Bug 16371] Standalone settings cannot be changed - Locked:revstandalonesettings.8. 

### PR DESCRIPTION
**Pull request by livecodepanos**
When you are on OS X card of Standalone Settings, and you modify an existing fld (i.e. "identifier"), then the closeField/returnInField/tabKey of group OSX is called. All these handlers used to call the propertyChanged handler of group OSX. 

In LC 8, the propertyChanged handler of revFrontscriptLibrary was called, instead of the  propertyChanged handler of group OSX.

The same happens for card Windows (see the script of group Windows).

This fix includes renaming the "propertyChanged" handler of group OSX to "OSXpropertyChanged", and make sure to rename all the calls to it in the script of OSX group. (Similarly for Windows).

### CODE REVIEW

**Comment by livecodepanos** [comment]
Binary diff:
https://gist.github.com/livecodepanos/755c67111dcb65f44a96

**Comment by livecodepanos** [comment]
Binary Diff:

https://gist.github.com/livecodepanos/a61256cd2d66ebf635e9

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a9ccb17

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a9ccb17cebae325dff98272979ce9de6e717eab9

**Pull request merged**
