### PR TITLE
[[ Cleanup ]] Remove gRevStackStatus global

### PR DESCRIPTION
**Pull request by livecodeali**
Once release-8.1.1 is merged up into develop, we can replace the remaining occurrence of `revSetEdited` in the standalone settings GUI and remove the `revSetEdited` function from the frontscript library.

### CODE REVIEW

**Comment by livecodeali** [comment]
Based on https://github.com/livecode/livecode-ide/pull/1427

**Comment by peter-b** [comment]
@livecodeali Is this now clear to merge?

**Comment by livecodeali** [comment]
@peter-b yes it is

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2bfe36a

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2bfe36a8ec9facb23b589f30d590338bb236b7bf

**Pull request merged**
