### PR TITLE
Enable substacks to be changed into main stacks using the PI

### PR DESCRIPTION
**Pull request by runrevelanor**
The Mainstack property option list of a sunstacks now includes the
substack, allowing it to be selected and set as its own mainstack,
turning it into a mainstack.

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f1b33fb

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f1b33fb25f4a1b6d7ff57f4eec67e16790266acf

**Comment by livecodeali** [comment]
@livecode-vulcan review not ok f1b33fb
@runrevelanor This is bug 16414 I think, not 17044. Could you change the bug fix note please?

**Comment by livecode-vulcan** [comment]
💔 review by @livecodeali not ok f1b33fb25f4a1b6d7ff57f4eec67e16790266acf

**Comment by livecodeali** [comment]
@livecode-vulcan review ok d9b64e8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok d9b64e8d5a8fcdcd0b54cc359ec63bfe8cd27409

**Pull request merged**
