### PR TITLE
Ensure you can open and close the SE more than once

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
This is odd - let's just merge for now though. Could you file a bug to investigate *why* this causes a problem?

**Comment by livecodeali** [comment]
@livecode-vulcan review ok b478747

**Comment by livecodepanos** [comment]
@livecodeali Sure, I'll file a bug

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok b478747ef34b0dfe18c6124a87bc34ebcab0a106

**Comment by livecodepanos** [comment]
Filed bug https://quality.livecode.com/show_bug.cgi?id=21827

**Pull request merged**
