### PR TITLE
[Bug 18176] Show up to 10 nested behaviors in the Project Browser

### PR DESCRIPTION
**Pull request by livecodepanos**
This PR is submitted on behalf of @BerndN, and it allows up to 10 nested behaviors to be shown in the PB. The behaviors are shown using oval graphics. Clicking on the graphic takes you to the script of the behavior. The tooltip of the graphic shows the long name of the behavior. See attached screenshots.

Thank you @BerndN :)

screen shot 2016-12-09 at 23 45 39

screen shot 2016-12-09 at 23 47 51

### CODE REVIEW

**Comment by BerndN** [comment]
@livecodepanos cool, thanks

**Comment by livecodeali** [comment]
@livecodepanos I think the bugfix note should be expanded to a multi-line note to describe the new feature (essentially how you have done in the PR comment above) so that it appears in the `IDE changes` section of the notes rather than just the list of bugfixes

**Comment by livecodepanos** [comment]
@livecodeali Thanks for the suggestion, PR updated :)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok fa4fedb

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fa4fedb420818072b0860e59fece1eb6a5c444c4

**Pull request merged**
