### PR TITLE
[[ SB Inclusions ]] Add substack for override confirmation dialog

### PR DESCRIPTION
**Pull request by livecodeali**
The libUrl script library inclusion would override the engine implementation
on mobile platforms, so this PR adds an appropriate dialog as a substack of
the standalone settings, which can be invoked by the standalone building scripts
as appropriate.

### CODE REVIEW

**Comment by livecodeali** [comment]
screen shot 2016-05-17 at 16 48 39

Code added to standalone settings stack:

```
command revConfirmInclusion pName, @rInclude, @rSilenceWarning
   set the cInclusion of stack "revStandaloneInclusionWarning" to pName
   modal stack "revStandaloneInclusionWarning"
   put the cInclude of stack "revStandaloneInclusionWarning" into rInclude
   put the cSilenceWarning of stack "revStandaloneInclusionWarning" into rSilenceWarning
end revConfirmInclusion
```

Code in dialog stack:

```
on preOpenStack
   set the loc of me to the screenLoc

   local tWarning, tInclusion
   put "The [[tInclusion]] inclusion has a built-in implementation" && \
         "for the platform you have selected. Retaining this inclusion may impair the" && \
         "functionality of your standalone application. Do you really want to include it?" \
         into tWarning

   put the cInclusion of me into tInclusion
   put merge(tWarning) into field "Warning" of me
   set the hilite of button "Check" of me to false
end preOpenStack

on optionSelected pInclude
   set the cInclude of me to pInclude
   set the cSilenceWarning of me to the hilite of button "Check" of me
   close this stack
end optionSelected

on mouseUp
   local tTarget
   put the short name of the target into tTarget
   if tTarget is "Remove" or tTarget is "Include" then
      optionSelected tTarget is "Include"
   end if
end mouseUp
```

**Comment by livecodeali** [comment]
Gist for last commit:
https://gist.github.com/livecodeali/f1445399ea767e1b2f62b5cc719f785a

**Comment by peter-b** [comment]
@livecode-vulcan review ok dae22c2

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok dae22c233bb4312da80cca86883776e817f5caa8

**Pull request merged**
