### PR TITLE
[[ IndicateCompilationErrors ]] Show errors in Project Browser

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
I have removed the WIP label now that the dependant PR has been merged.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 55d5a5b

**Comment by peter-b** [comment]
@montegoulding Please add a release note!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4a8b129

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4a8b129d2f1ef654a5e01fdda5e699c2f4340f65

**Pull request merged**
