### PR TITLE
Fixtests

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e480ccd

**Comment by montegoulding** [comment]
@livecodeali Did you want me to do a test PR on the livecode repo?

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e480ccd42f37a69203c13f3098d423e9082e1731

**Comment by livecodeali** [comment]
Probably best yeah, if that's ok

**Comment by montegoulding** [comment]
https://github.com/livecode/livecode/pull/5975

**Comment by montegoulding** [comment]
The second commit also applies to develop-8.2... not sure if the first does will check

**Comment by montegoulding** [comment]
I think I can just rebase this whole thing on 8.2

**Comment by montegoulding** [comment]
Test PR https://github.com/livecode/livecode/pull/5977

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 7d70977

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 7d70977e8c7db8b3bf039e4cbebd874024d38992

**Pull request merged**
