### PR TITLE
[iPad Pro 11] Added support for splash screens and icon

### PR DESCRIPTION
**Pull request by livecodepanos**
Binary changes:

In group "Icons":

the `...` button for icon selection has the following code:
```
on mouseUp
   chooseImageFileWithDimension "iPad Pro 11 Icon", "167,167"
end mouseUp
```
The `X` button for clearing the icon has the code:
```
on mouseUp
   clearSetting "iPad Pro 11 Icon"
end mouseUp
```
In group "Splash Screens":

the `...` button for splash screen selection has the following code, for portrait and landscape respectively:
```
on mouseUp
   chooseImageFileWithDimension "iPad Pro 11 portrait splash", "1668,2388"
end mouseUp

on mouseUp
   chooseImageFileWithDimension "iPad Pro 11 landscape splash", "2388,1668"
end mouseUp
```
and the `X` buttons for clearing the selected splash screens (for portrait and landscape respectively):
```
on mouseUp
   clearSetting "ipad pro 11 portrait splash"
end mouseUp

on mouseUp
   clearSetting "ipad pro 11 landscape splash"
end mouseUp
```

### CODE REVIEW

**Comment by livecodepanos** [comment]
Screenshot 2020-01-17 at 13 41 31

Screenshot 2020-01-17 at 13 41 21

**Comment by livecodeali** [comment]
@livecodepanos Can we take this opportunity to move the icons and splash screen groups up a bit? They look a bit weird where they are

**Comment by livecodepanos** [comment]
Screenshot 2020-01-20 at 17 03 29
Screenshot 2020-01-20 at 17 05 25

@livecodeali What do you think?

**Comment by livecodeali** [comment]
@livecodepanos yeah much better!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a78d40637e406b72901d5fc2df6ce168fae15a2b

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a78d40637e406b72901d5fc2df6ce168fae15a2b

**Pull request merged**
