### PR TITLE
[[ Android Archs ]] Add multiple android archs to IDE

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
depends on https://github.com/livecode/livecode/pull/6650

**Comment by montegoulding** [comment]
screen shot 2018-08-22 at 1 01 26 pm

**Comment by livecodeali** [comment]
@livecode-vulcan review ok bc118a3

**Comment by montegoulding** [comment]
I'm not sure why vulcan hasn't added the label but as this is reviewed I will merge

**Pull request merged**
