### PR TITLE
[[ Bug 16111 ]] RevSaveAs: build the path using the stack's filename,…

### PR DESCRIPTION
**Pull request by livecodesebastien**
… not it's stack name

### CODE REVIEW

**Comment by livecodeali** [comment]
I think this will work only if the stack already has a filename - otherwise you just get ".livecode" back as the result of revFixPath and it still opens the file dialog in an IDE folder.

**Comment by livecodeali** [comment]
I think we need to find where the defaultFolder has been set without being reset too.
@livecode-vulcan review not okay eccc775

**Comment by livecode-vulcan** [comment]
💔 review by @livecodeali not ok eccc77567a1f3b108c46089af09bdba88ce0863b

**Comment by livecodepanos** [comment]
I think in LC 6.7.x /7.x the defaultFolder is set on `startup` handler of the `Home` stack. It defaults to `/Applications` on OSX. In LC 8, these lines are missing from the `startup` handler. However, I tried to add them but the result is the same as described in the bug report. So my guess is that the defaultFolder is being set somewhere else too.

**Comment by peter-b** [comment]
@livecodepanos It looks to me as if it might be being set while loading LCB extensions and not restored as expected.

**Comment by livecodesebastien** [comment]
After a better look, the issue does not come at all from the IDE, but from the engine.
Superseded by https://github.com/livecode/livecode/pull/3024

**Pull request closed without merging**
