### PR TITLE
[Bug 17001] Ensure answer dialog is tall enough for icon

### PR DESCRIPTION
**Pull request by peter-b**
Make sure that the answer dialog is expanded vertically until it's
tall enough for the icon and balanced padding.

### CODE REVIEW

**Comment by peter-b** [comment]
``` patch
-- old  2016-02-24 11:55:42.000000000 +0000
+++ new 2016-02-24 11:51:01.000000000 +0000
@@ -240,7 +240,11 @@
    else
       put tWidth -12 - tAddition into tStartEdge
    end if
+   
+   -- [[ Bug 17001]] Ensure the dialog is tall enough for the icon + margin
    put the formattedHeight of field 1 of me + 58 into tHeight
+   put max(tHeight, the bottom of button "icon" + tIconTop) into tHeight
+   
    if tHeight > 400 then
       set the vScrollbar of field 1 of me to true
       put 400 into tHeight
```

**Comment by livecodeali** [comment]
I think you should possibly only do this if `tHasIcon` is true, otherwise a dialog without the icon will be too large

**Comment by peter-b** [comment]
Updated patch:

``` patch
--- old 2016-02-24 13:09:02.956956624 +0000
+++ new 2016-02-24 13:05:23.924198545 +0000
@@ -240,7 +240,13 @@
    else
       put tWidth -12 - tAddition into tStartEdge
    end if
+   
+   -- [[ Bug 17001]] Ensure the dialog is tall enough for the icon + margin
    put the formattedHeight of field 1 of me + 58 into tHeight
+   if tHasIcon then
+      put max(tHeight, the bottom of button "icon" + tIconTop) into tHeight
+   end if
+   
    if tHeight > 400 then
       set the vScrollbar of field 1 of me to true
       put 400 into tHeight
```

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 972f1f8

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 972f1f80abefa2556048d4a87802d7bfdba059b8

**Pull request merged**
