### PR TITLE
[[ Guides ]] Add guide list landing page

### PR DESCRIPTION
**Pull request by livecodeali**
This adds a landing page to the guides so that it loads quickly:
screen shot 2016-06-28 at 12 26 37

Also moved a lot of functions outside of the body of the `$(document).ready` callback, as there seemed to be no point in them being inside it.

### CODE REVIEW

**Comment by livecodeali** [comment]
Also incorporate the dropdown into the scrollspy list, as if they were all one document.
screen shot 2016-06-28 at 15 52 08

**Comment by peter-b** [comment]
@livecodeali Is it feasible to use the metadata we already provide in the guides about which type of guides they are to divide the guides into groups in the landing page?

**Comment by livecodeali** [comment]
@peter-b I thought about that, yeah, I think it is

**Comment by peter-b** [comment]
@livecodeali This all looks quite reasonable to me anyway.

@livecode-vulcan review ok 62f517f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 62f517f8bd89600b6735579c06dce20aaa434da6

**Comment by peter-b** [comment]
@livecode-vulcan review ok 2e44825

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 2e448255b395332fb970deb090868ba4264fe9bf

**Pull request merged**
