### PR TITLE
[Bug 18241] Removed ghost breakpoints from PB

### PR DESCRIPTION
**Pull request by livecodepanos**
Steps:
- Opened the msg box and typed:

```
set the breakpoints to empty
save stack revideprojectbrowser
```

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 738c39c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 738c39c47e00849a2ff7e83d408d07966dcefa98

**Comment by montegoulding** [comment]
I wonder if we can include this in our build process or linter or something...

**Comment by mwieder** [comment]
Note that this doesn't actually remove the breakpoint custom properties. See bug report #18241

**Pull request merged**
