### PR TITLE
[[ Plugins ]] Ensure plugin settings menu is up to date

### PR DESCRIPTION
**Pull request by livecodeali**
Just refreshes the list of plugins when the stack is opened.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Could you please put the script diff into a gist (or something)?

**Comment by runrevben** [comment]
@livecode-vulcan review ok 740fde1

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok 740fde154153ba1adc719335998e529142f7af74

**Comment by livecodeali** [comment]
Sure: 
https://gist.github.com/livecodeali/f2406f6d4d1351a1f501

**Comment by peter-b** [comment]
@livecodeali Well that was a even more straightforward than I was expecting...! :+1:

**Comment by livecodeali** [comment]
Hehe, still worth attaching though. Thanks for the reminder!

**Pull request merged**
