### PR TITLE
[[ Dictionary ]] Use browser widget for dictionary

### PR DESCRIPTION
**Pull request by livecodeali**
Unfortunately I can't work out the correct sequence of actions to get
the dictionary to load first time unless the browser widget is already
on the stack. So I've had to move the dictionary code into a behavior and
make the dictionary a binary stack for the time being.

### CODE REVIEW

**Comment by livecodeali** [comment]
Script: https://gist.github.com/livecodeali/0c47eccadb672d522353

**Comment by livecodeali** [comment]
Requires https://github.com/livecode/livecode/pull/3229

**Comment by peter-b** [comment]
@livecode-vulcan review ok 9accbb5

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 9accbb565f0886fc9f94395bfecd3ca5aefd1a17

**Pull request merged**
