### PR TITLE
[[ Bug 14217 ]] Fix PB keybaord nav in edit mode

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 23b814c

**Comment by livecodeali** [comment]
We really need some helper functions that clarify what on earth things like

```
(the selectedField is empty and (the selObj) is empty) or (the selectedField is not empty and revTargetStack(the long id of the selectedField) is not the short name of the topStack))
```

are supposed to actually be checking, don't we? :-)

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 23b814c3b05ea0173f1e9a026dbbdd92d35d2a48

**Comment by montegoulding** [comment]
@livecodepanos I just realised I forgot to investigate the return key issue and will do that today in a separate PR

**Pull request merged**
