### PR TITLE
Added ordering to the Project Browser.

### LINKED ISSUE #601: Project Browser: alphabetically order items in the Project Browser

### PR DESCRIPTION
**Pull request by runrevelanor**
An ordering preference has been added to the header options in the Project Browser. The stacks can be ordered by name or number. The default ordering is by name.

Closes #601

### CODE REVIEW

**Comment by peter-b** [comment]
I think GitHub will automatically link the issue if you mention the issue in your git commit message.  For example, if you write `Closes #601` in the commit message, then when the pull request is merged, the issue will be closed. See the GitHub docs: https://guides.github.com/features/issues/#notifications

**Comment by livecodeali** [comment]
@runrevelanor This seems to have acquired a conflict :-)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 902d2b2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 902d2b29d9c5f9180f0b3b428b0cf29d4e6a8f2c

**Pull request merged**
