### PR TITLE
Fixtests develop

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by montegoulding** [comment]
This is just here for testing we should merge in https://github.com/livecode/livecode/pull/5978 then merge up

**Comment by montegoulding** [comment]
OK so this now has some extra stuff needed for develop... probably if we merge these independently git will know what to do..

**Comment by livecodeali** [comment]
@livecode-vulcan review ok fd68045

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fd680451b4c5c991be8376cb492c94b30d1ac4ef

**Pull request merged**
