### PR TITLE
[Bug 16485] Support for adding icon and splash screen for iPad Pro 12.9

### PR DESCRIPTION
**Pull request by livecodepanos**
screen shot 2016-11-23 at 16 36 59

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos Is there any code in the group that changed?

**Comment by livecodepanos** [comment]
@livecodeali Yes I forgot to mention that.

In group "Icons":

the `...` button for icon selection has the following code:

```
on mouseUp
   chooseImageFileWithDimension "iPad Pro 12.9 Icon", "167,167"
end mouseUp
```

The `X` button for clearing the icon has the code:
```
on mouseUp
   clearSetting "iPad Pro 12.9 Icon"
end mouseUp
```

In group "Splash Screens":

the `...` button for splash screen selection has the following code, for portrait and landscape respectively:
```
on mouseUp
   chooseImageFileWithDimension "iPad Pro 12.9 portrait Splash", "2048,2732"
end mouseUp
```
```
on mouseUp
   chooseImageFileWithDimension "ipad pro 12.9 landscape splash", "2732,2048"
end mouseUp
```

and the `X` buttons for clearing the selected splash screens (for portrait and landscape respectively):
```
on mouseUp
   clearSetting "ipad pro 12.9 portrait splash"
end mouseUp
```
```
on mouseUp
   clearSetting "ipad pro 12.9 landscape splash"
end mouseUp
```

**Comment by livecodepanos** [comment]
@livecodeali I just double checked and realised I have missed the word `portrait` in the script of `X` button for clearing the portrait splash. I'll fix it now. Setting this to WIP

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f47263f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f47263f3c1e5c33c19a226d5dcc1373cab0f573e

**Pull request merged**
