### PR TITLE
[[ PI ]] Fix several issues with the gradient editor

### PR DESCRIPTION
**Pull request by livecodeali**
- Don't pop up editor when right-clicking
- Don't pop up color dialog when no stop is selected
- Use current stop color as preselect when popping up color dialog

This PR has slightly less in it than it looks, because some code that used
to be in a group script is now in the script-only behavior

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 899b7b2

**Comment by peter-b** [comment]
@livecodeali I think this might need a release note.

**Comment by peter-b** [comment]
@livecodeali Ah -- I see that we still can't handle GitHub bug numbers in V1-format release notes. Oh well!

@livecode-vulcan review ok 899b7b2

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 899b7b2f992710ba28716c8b9395b00de9c0ccc1

**Pull request merged**
