### PR TITLE
[[ Bug 17077 ]] Ensure gradient edit from PI triggers graphic edit mode

### PR DESCRIPTION
**Pull request by livecodeali**
This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/1069)

### CODE REVIEW

**Comment by peter-b** [comment]
The commit message for a82dac9 mentions changing `popupDismissed` and `editorPopup` into `after` handlers, but the actual changes that do that appear to be in 7e0d599.

@livecode-vulcan review ok 6b0fdd2

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 3 of 3 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/1069#-:-KE20f6YigFvn89QLqDE:-403531391)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 6b0fdd2cbdbd9abbe601c9b6e66981c24389396c

**Comment by livecodeali** [comment]
@peter-b Ok, have fixed up the commits so they reflect the messages.

**Comment by peter-b** [comment]
@livecode-vulcan review ok c4f69a8

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c4f69a8a62b7c2375ed7348c3b8c6ff5aec3f8d8

**Pull request merged**
