### PR TITLE
[[ Dictionary ]] Allow setting of currently displayed API entry from IDE

### PR DESCRIPTION
**Pull request by livecodeali**
The dictionary html has been reworked so that display of an entry is always triggered by the IDE

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali What happens on platforms where the browser widget isn't available (i.e. the dictionary stack doesn't work)?

**Comment by livecodeali** [comment]
Good point. What a pain.

**Comment by peter-b** [comment]
@livecodeali I'm worried that "Show API" might not be a very beginner-friendly menu entry.  What about "Show Documentation" instead?

**Comment by peter-b** [comment]
@livecode-vulcan review ok 01d70ce

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 01d70ce7247a095d96acdd759ab5707460a45ad5

**Pull request merged**
