### PR TITLE
[[ Bug 21122 ]] Update windowBoundingRect correction

### PR DESCRIPTION
**Pull request by bwmilby**
In **revmenubar.livecodescript**, `gREVRestore` was removed from the globals for `unIconifyStack`.
Restoring the global declaration.

### CODE REVIEW

**Comment by bwmilby** [comment]
@montegoulding This is the issue that I found and posted about on Gitter.

**Comment by montegoulding** [comment]
@bwmilby could you rebase against develop-9.0

**Comment by bwmilby** [comment]
@montegoulding I can, but when I look at the 9.0 branch it still has the global variable there.

**Comment by montegoulding** [comment]
hmm... let me check that PR

**Comment by montegoulding** [comment]
Should be in `develop-9.0` are you sure you pulled the latest?

**Comment by bwmilby** [comment]
I'm looking directly in GitHub.  The PR is flagged for 9.0.1 milestone but when I go to the actual commit:
https://github.com/livecode/livecode-ide/commit/a95287b9d4e885249c6a1eadb83f419e52d16017#diff-ab1e5441101d02107638ffee06997f4f
There is has "develop" as the branch.

https://github.com/livecode/livecode-ide/blob/develop/Toolset/palettes/menubar/revmenubar.livecodescript

https://github.com/livecode/livecode-ide/blob/develop-9.0/Toolset/palettes/menubar/revmenubar.livecodescript

**Comment by montegoulding** [comment]
@bwmilby aha! @livecodepanos beat you to it! https://github.com/livecode/livecode-ide/commit/17c5c0534b681e052ac5f029bf75052d8c25998f

**Comment by bwmilby** [comment]
Ok, so it just hasn't made it back into develop yet.

**Pull request closed without merging**
