### PR TITLE
Fonts Updated

### PR DESCRIPTION
**Pull request by macMikey**
The file sizes on some fonts have changed.
glyphicons-halflings-regular.woff2 is new.

### CODE REVIEW

**Comment by peter-b** [comment]
@macMikey The most important thing that I do when I review a pull request is to understand:
- the objective for the changes being made
- why these changes are the best way to meet the objective

The best way to make sure that I can understand this is if you write a [good commit message](http://chris.beams.io/posts/git-commit/) for your changes.  Unfortunately, this commit message is unclear.  I find myself asking:
1. What prompted @macMikey to make this PR? Did he find a bug that involved the fonts? Is this part of updating Bootstrap?
2. Where did @macMikey get the fonts from?
3. Why is the <kbd>woff2</kbd> file needed? Is it a new file or was it deliberately left out of the previous version?

When making contributions to an open source project, writing a clear commit message explaining your changes is the most reliable way to get your changes incorporated quickly and with a minimum of fuss.  [Here's an open source contribution I made recently to one of the projects that LiveCode uses.](https://cgit.freedesktop.org/cairo/commit/?id=b207a932a2d3740984319dffd58a0791580597cd)

**Comment by macMikey** [comment]
Peter,
I have explained to you, over private emails, bug reports, issue reports, and pull requests what is going on in the software, and what seems to fix it.  I see that you want things to be done in a certain way, so I hope I have explained well enough what to do.

**Comment by peter-b** [comment]
@macMikey You have explained to me, but you haven't explained to @livecodefraser, for example.  It's very important that all changes to LiveCode can be understood by _anyone_.  Who knows who the next person who will work on the dictionary will be?

I haven't asked you to do anything that I wouldn't ask anyone on the core development team to do when making contributions.  I'm really sorry that this is clearly frustrating for you.  As and when I get the opportunity, I will work to improve how we document our contribution process.

**Comment by macMikey** [comment]
Figure out what the goal is, and remove everything that is an impediment to achieving it.  This experience has been an impediment to my direct involvement.  The process of trying to address documentation issues is an impediment to my direct involvement in that project.
I don't need credit or kudos or a consulting gig.  I can just as easily do what I want to do via bug reports.  You already have all my notes on what the problem seems to be, what to do and why, so hand them off to someone else or have at it.

**Comment by livecodeali** [comment]
@macMikey We can surely both agree that the ideal scenario is you submitting pull requests which require no changes. It means you don't have to do any additional git wrangling and our reviewing job is easier. I think you are being a little unfair on @peter-b, who is merely trying to help you get to the stage where you submit a pull request and it is accepted without any required changes (for both of our sakes).

We can't be expected to submit pull requests for things even when every step of what needs to be done has been described - we still need to allocate our time according to our current priorities and what we have the resources for. Having your notes on what the problem is doesn't mean the priority of the fix is necessarily any higher, or that we can afford to spend time on it. On the other hand, it _is_ definitely better than nothing, and a contribution in itself, so thank you for that! 

Currently the docs that we do have appear to be lacking. In order for us to rectify this, we need to know exactly what would help you. Take a look at [this PR](https://github.com/livecode/livecode/pull/3518) for example, which resulted in materially better documentation. Unfortunately, at the moment we also don't have the resources to create comprehensive documentation on what we expect from commit messages, although @peter-b has posted something to the list to that effect, which I will copy here:

```
0. Be willing to go away and learn things by yourself.  The core
development team is very small and very busy and we won't necessarily
have time to closely guide you through using normal development tools in
the normal way.

1. Discuss your plans with someone on the core dev team before you start
work.  You will eventually need to get someone who's on the dev team to
merge your changes -- so it is _important_ to get one of us involved
(and interested) as early as you possibly can!

2. Follow the coding style.  Make your code as clear and easy to read
and understand as possible.  Name things carefully.

3. Make each change as small as possible.  It's far, far easier to get
100 changes with 10 lines of code merged than it is to get a single
1000-line change merged.

4. Spend time on writing your git log messages and your GitHub pull
requests so that they really clearly describe the changes you've made
and why you've made them.  This is a good guide:
http://chris.beams.io/posts/git-commit/

5. Be prepared to revise your changes.  We want to help you get your
changes committed, but they will need to fit in properly with the things
that we're trying to achieve.
```

Additionally, in terms of the docs project, I don't believe it was the process that was your impediment. You were attempting to change the wording of a very important section of documentation. Doing this is naturally going to create dialog and require changes, which in turn tends to require using more features of Git than are available via the web interface. By contrast, look at your own contribution to the clock widget, for example. It was a one-line change to code which unambiguously improved the widget. It was therefore accepted without revision.

**Comment by macMikey** [comment]
Hey, Ali,
I totally disagree.  In my opinion, the ideal scenario is getting any and all volunteers involved in a way that keeps them involved so we can leverage their time and effort to make the project better.  

I spent a LOT of time figuring out what the heck was going on, and then I spent a lot more working on fixing it.  Then I spent a lot of time submitting thoughts what I thought was the right way before I wasted a lot of time unsuccessfully fighting with git so I could make the submissions before getting all of them rejected because they weren't done correctly.

Let's stop wasting your time and way, way, way more importantly, let's stop wasting mine.  You want the documentation a certain way, so make it that way!  Peter wants the project submissions done a certain way, so he get them them that way.  I'm going to submit bug reports, and, when I have something constructive to say about the report, I'll add it to the report.

**Comment by livecodeali** [comment]
Well, your ideal scenario is talking about a completely different thing. You might as well say "I disagree, the ideal scenario is world peace". Both your and my ideal scenarios are ideal for the thing they're actually talking about.

Not a single one of your submissions has been rejected, all that has been asked of them is that they meet the required standards for the project we maintain. The requests in almost all cases were extremely specific, and had they been followed would have resulted in accepted submissions.

Anyway, good to know that you feel your time is more important than mine. I shall bear it in mind.

**Pull request closed without merging**
