### PR TITLE
[[ IDE ]]  Unify property definition files and parsing

### PR DESCRIPTION
**Pull request by livecodeali**
Also fixes bug 16369, since that was partially an issue with the availability of the styledText property to the PI

[Review on Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/667)

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Would this be a good time to add a document with a description of the property info file format?

**Comment by livecodeali** [comment]
@peter-b yes!

**Comment by peter-b** [comment]
It's quite hard to tell, by reading a property info file, which column a particular value is in.  Also, most properties only seem to set a value in the `Default` column.  Would it make it easier to maintain the property info files if you could optionally use named values, e.g. `traversalOn Default=false`?

It would also be nice if the property parsing code didn't need trailing whitespace (in the form of "extra" tab characters)

Of course both of the above points are moot if there's already a nice property info-editor stack that I don't yet know about :grinning: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 36 of 37 files at r7, 1 of 1 files at r8.
Review status: 41 of 42 files reviewed at latest revision, 2 unresolved discussions.

---

_[Toolset/libraries/revidelibrary.8.livecodescript, line 302 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-K3Q6TE-zAPkgo6pR7ix:-K3Q6TE-zAPkgo6pR7iy:-1064355206) ([raw file](https://github.com/livecode/livecode-ide/blob/74e66db34e6942af1f91a8ee9b7739d947794694/Toolset/libraries/revidelibrary.8.livecodescript#L302)):_
If you made a single constant that looked like:

```
"name:1,label:2,..."
```

then you could `split` it to use it both in `__propertyDataNameToItemNumber` and in `__propertyDataNames`.

---

_[Toolset/libraries/revidelibrary.8.livecodescript, line 418 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-K3Q6rk6oYhKnhrA-IxX:-K3Q6rk6oYhKnhrA-IxY:1393850683) ([raw file](https://github.com/livecode/livecode-ide/blob/74e66db34e6942af1f91a8ee9b7739d947794694/Toolset/libraries/revidelibrary.8.livecodescript#L418)):_
Should this use `__propertyDataNames`?

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-:-K3Q7sjVPkqV7JTzSZ14:1437521399)_

**Comment by livecodeali** [comment]
Hmm, yeah - I always just view it in a field with appropriate tabStops - but it might be nice to provide an editor stack.

It doesn't actually need the trailing whitespace either (as item x of ...  will always be empty anyway when x exceeds the number of tabbed items) - they've arisen just because of the way I've edited it.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-:-K3QDPXaObzbAv6wOHMm:926615519)_

**Comment by livecodeali** [comment]
_[Toolset/libraries/revidelibrary.8.livecodescript, line 302 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-K3Q6TE-zAPkgo6pR7ix:-K3QE6UIe9uidOMDEbY9:441559367) ([raw file](https://github.com/livecode/livecode-ide/blob/74e66db34e6942af1f91a8ee9b7739d947794694/Toolset/libraries/revidelibrary.8.livecodescript#L302)):_
good plan

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667)_

**Comment by livecodeali** [comment]
_[Toolset/libraries/revidelibrary.8.livecodescript, line 418 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-K3Q6rk6oYhKnhrA-IxX:-K3QEYBfbNB5Nm0pyIMZ:233942616) ([raw file](https://github.com/livecode/livecode-ide/blob/74e66db34e6942af1f91a8ee9b7739d947794694/Toolset/libraries/revidelibrary.8.livecodescript#L418)):_
Yeah I guess that would make sense

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667)_

**Comment by peter-b** [comment]
Review status: 41 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

_[Toolset/libraries/revidelibrary.8.livecodescript, line 418 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-K3Q6rk6oYhKnhrA-IxX:-K3QFLrZibsz4OvVl6GO:1204155306) ([raw file](https://github.com/livecode/livecode-ide/blob/74e66db34e6942af1f91a8ee9b7739d947794694/Toolset/libraries/revidelibrary.8.livecodescript#L418)):_
Looking at this again there might be an issue because `__propertyDataNames` includes `options` whereas this list doesn't.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667)_

**Comment by livecodeali** [comment]
_[Toolset/libraries/revidelibrary.8.livecodescript, line 418 [r7]](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-K3Q6rk6oYhKnhrA-IxX:-K3QLnq1DKJ5HDZs2UP3:616680096) ([raw file](https://github.com/livecode/livecode-ide/blob/74e66db34e6942af1f91a8ee9b7739d947794694/Toolset/libraries/revidelibrary.8.livecodescript#L418)):_
It should be ok to have extra stuff in tDataA[tPropName]. In fact, I think I can just put everything from tLineDataA into tDataA[tPropName]

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667)_

**Comment by peter-b** [comment]
@livecode-vulcan review ok 1681a34

---

Reviewed 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/livecode/livecode-ide/667#-:-K3QP9mRMTugCwm3pty-:-1251250268)_

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 1681a34d2099d40dceb76a5b8df8d4d28c728652

**Comment by livecodeali** [comment]
@peter-b Sorry, just tweaked that last commit slightly!
(I had put `__propertyDataMapping` instead of `__propertyDataMapping()`)

**Comment by peter-b** [comment]
Superseded by #678!

**Pull request closed without merging**
