### PR TITLE
[[ Bug 15788 ]] Tokenise search string and find entries containing all of them

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali: Are you sure you want to keep the `console.log()` calls in production?

**Comment by runrevben** [comment]
we should look at applying this to the web too.. Is there a way of marking this as something to return to?

**Comment by runrevben** [comment]
@livecode-vulcan review ok 33651e2

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok 33651e2639e621e6d3fe82bb26177ce2575fdd16

**Comment by livecodeali** [comment]
@peter-b good shout, I forgot to remove them.

**Comment by livecodeali** [comment]
@runrevben yes, we need a way for someone (me?) to be able to update the online docs, or ideally to automate it. We can add a new tag for revisiting if you want.

**Comment by livecodeali** [comment]
@livecode-vulcan review by @runrevben ok d98e97a

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok d98e97a26b28da191b7da013c27571f0842c5a16

**Pull request merged**
