### PR TITLE
[Bug 16132] Fix typo that prevents backdrop from working

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodesebastien** [comment]
@livecode-vulcan review OK c97c067

**Comment by peter-b** [comment]
I really don't think the "fixed typo" comment is provides any real value here... :confused:

**Comment by livecodesebastien** [comment]
Good point. Can you remove the comment Panos?
@livecode-vulcan review not ok c97c067

**Comment by livecode-vulcan** [comment]
💔 review by @livecodesebastien not ok c97c067cb402550f751942a81a94815e8cd05ab9

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 91b7a11

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 91b7a11c583c27f76f0761357cdafd5b8f0dbcf9

**Pull request merged**
