### PR TITLE
Prevent unnecessary disk writes of revPreferences stack

### PR DESCRIPTION
**Pull request by livecodepanos**
Thanks @livecodeali and @montegoulding for the code suggestion.

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecode-vulcan review ok aabe67c

@livecodepanos `revInternal__SavePreferences` also throttles saving to at most once per 500 milliseconds. Perhaps that should be extended out a bit longer. Probably it could go a lot longer (a minute?) given we force saving prefs on shutdown.

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok aabe67c4d6657212d5a33621d91a2e1b16d3b9db

**Comment by livecodepanos** [comment]
@montegoulding I am wondering if 1 minute is too much? I have changed it to 30 seconds for now. WDYT?

**Comment by montegoulding** [comment]
30 seconds should be fine

@livecode-vulcan review ok b0bd839

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok b0bd8396d8edf70eaf7c1eed19061fb235307851

**Pull request merged**
