### PR TITLE
Improve the Start Center UI on Mac

### PR DESCRIPTION
**Pull request by runrevelanor**
Update the font, text size and size of fields to ensure text is not
cut off.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok c5f1130

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c5f1130b8906837f4bba3ed04333cd83bdb59f6b

**Comment by peter-b** [comment]
@livecode-vulcan review ok 80cf4df

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 80cf4dfb75baafcd8c117d80ffe4a763fc7ce111

**Pull request merged**
