### PR TITLE
[[ Bug 16242 ]] Make sure defaultFolder is always restored

### PR DESCRIPTION
**Pull request by livecodeali**
- Reworked revIDEStoreDefaultFolder and revIDERestoreDefaultFolder
  so that it is safe to have nested calls to them.
- Enclosed instances of setting the defaultFolder with store/restore
  pairs where possible (i.e. only when ide library handlers are definitely
  available)

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Total bikeshed: is this an opportunity to use `revIdePushDefaultFolder` and `revIdePopDefaultFolder` instead?

**Comment by livecodeali** [comment]
Sounds good

**Comment by peter-b** [comment]
@livecodeali Another suggestion (sorry): what about making `revIDEPushDefaultFolder` take an optional `pFolder` argument? This would simplify the common case:

```
revIDEPushDefaultFolder
set the defaultfolder to "/foo/bar"
/* ... */
revIDEPopDefaultFolder
```

to

```
revIDEPushDefaultFolder "/foo/bar"
/* ... */
revIDEPopDefaultFolder
```

**Comment by livecodeali** [comment]
Seeing as this branch is now in conflict, I don't see why not.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 41addea

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 41addea25c3ea2ada03bcbdeb3919defab5d91af

**Comment by livecodeali** [comment]
Trivial (whitespace) merge conflict.

**Comment by peter-b** [comment]
@livecode-vulcan review ok 4ae7902

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 4ae7902596f0f77b5b403f3a418eec1ce9fc3db1

**Pull request merged**
