### PR TITLE
[[ Bug 18491 ]] Allow substack to become a mainstack via PI

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Do you think this change deserves a long-form release note explaining where to find the new control?

@livecode-vulcan review ok 39df76f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 39df76f0d86b76a3377ef6afaf9ca1fedd33fbfb

**Comment by livecodeali** [comment]
@peter-b Yeah that's a good shout.

**Comment by peter-b** [comment]
@livecode-vulcan review ok f48607f

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok f48607f96b5ae5f79de1f7407806bf471726ba30

**Pull request merged**
