### PR TITLE
[[ Bug 17660 ]] Ensure ideSelectedObjectChanged message is sent by the IDE

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
Under the current system of the IDE, this should actually `lock messages` around the `do "select..` and then `ideMessageSend "ideSelectedObjectChanged"` after unlocking. (see note here http://quality.livecode.com/show_bug.cgi?id=18076)

However, maybe it's time to change that and remove all such lock messages in the IDE library.

**Comment by montegoulding** [comment]
Hmm... I see no real reason to deliberately lock messages here. I'm not overly sold on the idea that anything the IDE does to user stacks will be done in a lock messages environment although it does avoid the every plugin has a frontscript

**Comment by montegoulding** [comment]
@livecodeali I will patch this and we can cross this bridge later

**Comment by livecodeali** [comment]
I think you're right, but I also think for consistency this should do what everything else does for now, until we change everything.

**Comment by montegoulding** [comment]
I notice there's lots of `lock messages` then `unlock messages` in the code near here also which probably needs to to what I've done here and store the `lockMessages` for resetting.

**Comment by montegoulding** [comment]
http://quality.livecode.com/show_bug.cgi?id=18218

**Comment by montegoulding** [comment]
@livecodeali I have updated the note and commit summary to reflect the changes to the patch

**Comment by livecodeali** [comment]
@livecode-vulcan review ok fec463c

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok fec463c248532d0af8c73288dc994818cda3ce00

**Pull request merged**
