### PR TITLE
Create behaviors from script only stacks in behavior area of PI

### PR DESCRIPTION
**Pull request by trevordevore**

### CODE REVIEW

**Comment by trevordevore** [comment]
I'm not sure about the wording in the menus. Open to other suggestions.

**Comment by livecodeali** [comment]
For the sake of discussion the new menu items are
```
Create behavior from new script only stack
Create behavior using control script and script only stack
```

I have no problem with the first one, the second one may be slightly unclear. I'm not completely sure how to make it better though.

Maybe it should be another submenu:
```
Create behavior from script only stack
   - create new  (or create empty?)
   - use existing control script
```

**Comment by trevordevore** [comment]
@livecodeali What about this?
d0003977-efc3-4565-bda9-c3876f182e28

**Comment by livecodeali** [comment]
@trevordevore That works for me!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok a1d11d2

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok a1d11d22d6b74d9659542b274bc6a529c75ede8c

**Pull request merged**
