### PR TITLE
[Bug 17470] Make sure arrowKey is sent

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok e0a02d3

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok e0a02d3df9b979c7f6d7c7b529a11241de87d393

**Comment by livecodepanos** [comment]
I am setting this to WIP for now. Although this patch does fix the problem, it is not present in the previous (working as expected) versions (i.e. LC 7.1.4).

**Comment by livecodepanos** [comment]
Replaced by https://github.com/livecode/livecode-ide/pull/1197

**Pull request closed without merging**
