### PR TITLE
[[ Community Docs ]] LiveCode Script Guide updates

### PR DESCRIPTION
**Pull request by asayd**
- Removed reference to QT needed for Windows media playback.
- Line continuation character doesn't need to be escaped.
- Other minor formatting fixes.
- Changed references to "text boxes" to "note styles".
- Updated description of LiveCode documentation resources.
- Revised and updated description of Start Center.
- Links to new image resources.

### CODE REVIEW

**Comment by asayd** [comment]
@livecodeali Trying to create PR for updates to Script Guide. I think I successfully uploaded new images, but not sure it worked.

**Comment by livecodeali** [comment]
@asayd Yep, that worked! You should be able to make the text changes and upload the images in the same PR, but it'll be alright when they're both merged

**Comment by livecodeali** [comment]
@asayd There is a slight issue here in that I'm currently tracking the 8.0.x releases with community-docs, whereas some of these changes (i.e. the Quicktime change) relate only to the 8.1 releases. So could you resubmit this PR (and the images one) against develop please?

**Comment by asayd** [comment]
@livecodeali Should I roll back the QuickTime change on the PR that's on community-docs, as well as resubmitting to develop (with the QT change)? Or just cancel the PR on community-docs altogether? I'm still trying to figure out which branch is for what.

**Comment by livecodeali** [comment]
@asayd What you've done is fine, we can live with the changes not being in the 8.0.2 releases!

**Pull request closed without merging**
