### PR TITLE
[[ Default Handlers ]] Various fixes

### PR DESCRIPTION
**Pull request by livecodeali**
- [x] Prevent removal of P from handler name
- [x] Make default handler name grey in list
- [x] Fix spacing of default handler list
- [x] Add SE preference for showing list

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodeali I have added a note to 20066 to Hungarianize the params. Particularly important as some params will be reserved words.

**Comment by livecodeali** [comment]
The existing ones are dealt with here: https://github.com/livecode/livecode/pull/5693

But I agree, no reason not to make absolutely sure wherever possible! Particularly as we will not have control over the widgets' ones.

**Comment by montegoulding** [comment]
Hmm... it is probably best to deal with it via the docs so they are the same in both places. We should add a test to ensure that messages have hungarianized parameter names.

**Comment by livecodeali** [comment]
screen shot 2017-07-15 at 15 53 16
screen shot 2017-07-15 at 15 53 26
screen shot 2017-07-15 at 15 53 37

**Comment by runrevmark** [comment]
@livecode-vulcan review ok 532246b

**Comment by livecode-vulcan** [comment]
💙 review by @runrevmark ok 532246b0753a865cda16fc87816456d5267a97e6

**Pull request merged**
