### PR TITLE
[Bug 16464] Prevent script execution abort when resizing stack

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
Instead of that whole clause:

```
    if there is a stack "message box" then
       ...
    end if
```

you can just call `revSetActiveStacks`.

This will send `ideActiveStacksChanged` to all stacks that have subscribed to this message.

**Comment by livecodeali** [comment]
Hmm, actually that will only work if the active stack has actually changed. I wonder what this was used for...

**Comment by livecodeali** [comment]
Ok, I'm pretty sure that whole clause

```
 if the environment is "development" then
...
end if
```

can be deleted!

Nothing should need to manually update the active stacks anymore, and the previous section is just to make the old property inspector work - the new property inspector detects property changes without having to be manually updated.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 01de046

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 01de046ac355f1c455c4740f2df0a41962f68e36

**Pull request merged**
