### PR TITLE
[Bug 4010] Ensure Image/Object Library places objects only on user's stack

### PR DESCRIPTION
**Pull request by livecodepanos**
Changes:

 - in the script of `button "Insert Image into Stack" of group "Buttons" of card "Images" of stack "revimagelibrary"`

- in the script of `button "Insert Reference into Stack" of group "Buttons" of card "Images" of stack "revimagelibrary"`

- in the script of `button "Insert Into Stack" of group "Buttons" of card "Objects" of stack "revimagelibrary"`

added this check in the very beginning of the `mouseUp` handler of those buttons:

```
if isInvalidTarget() then
   exit mouseUp
end if
```

In the script of stack "revImageLibrary", added the following handler:

```
function isInvalidTarget
   if the _ideoverride of the topstack then
      answer warning "Please open a stack first"
      return true
   end if
   return false
end isInvalidTarget
```

Moreover, declared any variable used in those scripts, since compilation failed under Strict Compilation Mode

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodepanos I think you should use this here:
```
if not revIDEStackIsIDEStack(the topStack) then
   exit mouseUp
end if
```

**Comment by livecodepanos** [comment]
@montegoulding I have updated the PR. Now I use this check in the mouseUp handler of the 3 buttons:

```
if revIDEStackIsIDEStack(the topStack) then
   answer warning "Please open a stack first"
   exit mouseUp
end if
```

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 24c3059

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 24c30590d6057d925cc67866f7cf5da58f1a4bac

**Pull request merged**
