### PR TITLE
[[ Brackets ]] Bracket completion

### PR DESCRIPTION
**Pull request by montegoulding**
When rebasing this I found a rather serious issue which is Bug commit here. I will submit a separate PR so that can be merged ASAP.

### CODE REVIEW

**Comment by runrevmark** [comment]
@montegoulding I think the bug fix PR was merged the other day - https://github.com/livecode/livecode-ide/pull/1620

**Comment by montegoulding** [comment]
ah, yes I'll rebase

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8ac310e

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8ac310e912063689395ceb4dd778803e1fc35ec8

**Pull request merged**
