### PR TITLE
[[ Bug 14863 ]] Native scrollers on DataGrid

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
It's probably worth creating an auxiliary function for
```
return the environment is "mobile" and \
   sScrollerId is not empty and \
   sScrollerId is among the lines of mobileControls()
```

**Comment by montegoulding** [comment]
Done... good idea!

**Comment by livecodeali** [comment]
@livecode-vulcan review ok f32fe24

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok f32fe24b2c9374934441195208f4042fa77cc9ec

**Pull request merged**
