### PR TITLE
[[ Bug 21514 ]] Automatically select text of fields in PI

### PR DESCRIPTION
**Pull request by bwmilby**
Add `openField` handler to select the text of fields. For the custom
properties behavior, when a key is selected in the tree view widget, then
the corresponding key text will also be selected.

### CODE REVIEW

**Comment by montegoulding** [comment]
@bwmilby I think we have an issue now that we merged the tree view patch with a note for bug 20503. I think we will need to open a new report just to track the auto text selection.

**Comment by bwmilby** [comment]
Filed new bug report, referenced in the original, updated note file name.

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 2a73480

Thanks @bwmilby !

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 2a73480c084518f06edfa4d59bb3e0b7bc8e16b0

**Pull request merged**
