### PR TITLE
[[ Bug 16025 ]] Use actual dg object rather than snapshot when dragging out

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevben** [comment]
Hey Ali, what was the thought behind this? Looks like a solid update which I can mark review ok.. just wondering what prompted the change.

**Comment by livecodeali** [comment]
For some reason taking a snapshot of the datagrid doesn't work - so when datagrids are dragged out they are just a line. I can't work out why this is, so it seemed reasonable just to revert to the old behavior in that specific case.

**Comment by runrevben** [comment]
Ah, makes complete sense!

**Comment by runrevben** [comment]
@livecode-vulcan review ok aac5d7e

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok aac5d7ee18fc73069f06cbc66cb65df4210642f0

**Comment by livecodeali** [comment]
There was a trivial merge conflict here.
@livecode-vulcan review by @runrevben ok 6303b53

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok 6303b535d8d10a8b17eda478f26873fdc05c3353

**Pull request merged**
