### PR TITLE
[Bug 19978] Create missing folder if necessary

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecodepanos I would tweak the beginning of that handler to get the support folder, rather than having to 'unparse' it, i.e.
```
local tSupportFolder, tDefaultScript, tTargetStack
put pFolder & "/support" into tSupportFolder
put tSupportFolder & "/defaultscript.livecodescript" into tDefaultScript
```

**Comment by livecodepanos** [comment]
Good point @livecodeali, I'll update the PR :)

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 39553e0

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 39553e07af5319866be203e31994852725954de8

**Pull request merged**
