### PR TITLE
[[Community docs]] Update DG Guide to LC8.1 IDE, add Tips and Tricks 

### PR DESCRIPTION
**Pull request by jameshale**
1. Update all images to use new LC8.1 IDE
2. Update text to new terminology to match LC 8.1 IDE
3. Modify text where appropriate to improve clarity.
4. Adjust image positions from original layout.
5. Incorporate most of Tips and Tricks manual.

---

This change is [Reviewable](https://reviewable.io/reviews/livecode/livecode-ide/1251)

### CODE REVIEW

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 116 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRYvcF7p9oemATWZZc:-KLRYvcF7p9oemATWZZd:1314232476) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L116)):_

> ``` Markdown
> #### Customizing Columns####
> 
> Now that you've populate a Data Grid Table with some data let's look at
> ```

populate -> populated

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
@jameshale I'm going to go through this and just note anything I notice whether it is related to your changes or not - they won't necessarily all need to be fixed before I accept the pull request, so don't worry if there are a lot!

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 195 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRZmRL1XBX6QtqZ1-R:-KLRZmRL1XBX6QtqZ1-S:1806501793) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L195)):_

> ``` Markdown
> #### Change Style to "Form" ####
> 
> Select the Data Grid and open the LiveCode property inspector. Change
> ```

Property Inspector should be title-cased for consistency

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 475 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRaBnb49J2GOcaYfif:-KLRaBnb49J2GOcaYfig:-1524872689) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L475)):_

> ``` Markdown
> 
> It is called by a button placed on the card **Populate Data Grid**. 
> The script of the button being...
> ```

I think this could just be

```
It is called by a button placed on the card **Populate Data Grid** with script
   on Mouseup
      uiPopulatePeople
    end Mouseup
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 503 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRaf3RqHZjAf9I4zhw:-KLRaf3RqHZjAf9I4zhx:-195131562) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L503)):_

> ``` Markdown
> 
> 
> You can either  change the height of the row template by updating the 
> ```

There's a double-space between either and change here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 653 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRbBuFVPx2ryR06H_g:-KLRbBuG0LUOIq75Ce0k:1671900505) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L653)):_
Most of our blockquote notes are formatted as follows:

```
>*Note:* <text of note>
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 810 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRbhX6XDl9KkJezf8e:-KLRbhX7fQa9OqcqKlp3:152283866) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L810)):_

> ``` Markdown
> after a column in our table. This control is located in the row
> template group for our data grid. This lesson will discuss how to
> create templates for columns in a data grid table.
> ```

You've changed a few `your`s to `our`s here - as you have been changing `I` and `we` to `you`,  I think they should have stayed as `your`s.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 901 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRd9Rq3n2YB5zqbKLa:-KLRd9Rq3n2YB5zqbKLb:697508526) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L901)):_

> ``` Markdown
> automatically assigns the ***dgLine*** and the ***dgIndex*** property when
> displaying the row.
> ```

The convention that seems to be present in the LiveCode Script guide is that syntax is bold and variables are italic, so I think these dgProps should not be italicised

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 1010 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRe1aSSxQUNSSN33ES:-KLRe1aTcoPxvz_mlUDj:1229529778) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L1010)):_

> ``` Markdown
> example that could be used in a Data Grid *form* behavior script:
> 
>     ##Data Grid Row behaviour script
> ```

We use the American spelling of behaviour!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 1119 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLReTdQXKI4yKv9PSQk:-KLReTdRGtn9QZv1Iw2P:419797001) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L1119)):_
Perhaps this should be 

```
>*Important:* This example script...
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 1599 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRfCJoKHa6rdQoG-PC:-KLRfCJpPBMA1eObZRGt:1078772033) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L1599)):_

> ``` Markdown
> **Label** field in the row template. We will do this using the **Project Browser**
> 
> >You need to stop editing the group before returning to the **Project 
> ```

This should probably be a `>*Note:*`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 1658 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRfPnD-D64VqQx-1JD:-KLRfPnD-D64VqQx-1JE:-2009719723) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L1658)):_

> ``` Markdown
> #### Update LayoutControl and ResetData ####
> 
> The LayoutControl and ResetData handlers also have references to the Label field which 
> ```

I guess LayoutControl and ResetData should be bold here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 1695 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRfZI1mdKStcnADIPX:-KLRfZI1mdKStcnADIPY:-411832931) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L1695)):_

> ``` Markdown
> the dgData array properly represents what is being seen in the
> interface. You can do this in the mouseUp handler of the behavior
> script.
> ```

And `dgData` and `mouseUp` should be bold

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2048 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRhaerosmDldgl-0Um:-KLRhaerosmDldgl-0Un:-401961122) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2048)):_

> ``` Markdown
> 
> In the following example only the dgHeader property returns the long id of a
> control (1) because even thought the click was in the table header it was not on a column
> ```

thought -> though

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2150 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRhugdi-wuUfPrvbYT:-KLRhugdi-wuUfPrvbYU:27139622) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2150)):_

> ``` Markdown
> Alternatively you can create your own custom column template for a
> particular column. This allows you complete control over the look and
> feel of the column. See the lesson on *[How Do I Customize A Table's Columns?][]*
> ```

This should probably be 

```
See section [How Do I Customize A Table's Columns?](#How Do I Customize A Table's Columns?)
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2150 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRhugdi-wuUfPrvbYT:-KLRiM4YNAlPMakkPebc:1090131016) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2150)):_
<details><summary>

<i>Previously, livecodeali (Ali Lloyd) wrote…</i></summary>



> This should probably be 
> 
> ```
> See section [How Do I Customize A Table's Columns?](#How Do I Customize A Table's Columns?)
> ```
> 
> </details>
> actually
> 
> ```
> See section [How Do I Customize A Table's Columns?](#how-do-i-customize-a-tables-columns)
> ```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2209 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRjrfZPmMl39vcSPFX:-KLRjrfZPmMl39vcSPFY:-1038778415) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2209)):_

> ``` Markdown
> of a row template and this will display the line number for the current
> line. In LayoutControl you just need to ensure the rect of the field so
> that it fills the entire cell (2).
> ```

I think the 'so that it' should be deleted here ('ensure the rect of the field fills the entire cell (2)')

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2256 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRkLrByv7nV9xg47KP:-KLRkLrByv7nV9xg47KQ:-1446306270) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2256)):_

> ``` Markdown
> ["sort by column"] property is set. This includes when the user clicks on a column header
> to sort that column. By placing our own version of the **SortDataGridColumn** in the 
> script for our data grid we can capture this message and modify how it works.
> ```

our -> your and we -> you

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2281 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRkWYLT-M0I2K402YX:-KLRkWYLT-M0I2K402YY:-272522628) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2281)):_

> ``` Markdown
>     end SortDataGridColumn
> 
> The way our **SortDataGridColumn** works is simple. If you pass the message then
> ```

maybe `The way the **SortDataGridColumn** handler works is simple.`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2291 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRkh5DKY_g9h5iYTP1:-KLRkh5DKY_g9h5iYTP2:1316545827) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2291)):_

> ``` Markdown
> exists, so we call **ReverseSort** which is a built-in data grid helper that reverses 
> whatever the current sort order is(2).
> ```

All these `we`s should probably be removed by changing this section to the passive voice.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2376 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRl1gkWuuop-pSvZll:-KLRl1gkWuuop-pSvZlm:-646218361) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2376)):_

> ``` Markdown
> message is sent to the Data Grid. By intercepting this message and not
> passing it we can effectively disable sorting.  For more information
> about how SortDataGridColumn works please see [How Do I Customize Column Sorting?][].
> ```

Similarly, I think 

```
[How Do I Customize Column Sorting?](#how-do-i-customize-column-sorting)
```

should work here to link internally

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2565 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRlU9h_UQDcOgIb_aL:-KLRlU9i9e0PPQvEUN9h:-818577810) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2565)):_

> ``` Markdown
> "the target" (2) Of course the **ForEditing** field has no text in it and by default 
> and so we need to combine  
> ```

Some more `we`s here!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by jameshale** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2376 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRl1gkWuuop-pSvZll:-KLRlTQridaIFDXrTALn:1038823023) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2376)):_
<details><summary>

<i>Previously, livecodeali (Ali Lloyd) wrote…</i></summary>



> Similarly, I think 
> 
> ```
> [How Do I Customize Column Sorting?](#how-do-i-customize-column-sorting)
> ```
> 
> should work here to link internally
> </details>
> Can I just re-edit the raw .md file that is linked to the pull request to do this stuff or do I need to do something else?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 3632 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRlybae40fPZP41TDT:-KLRlybae40fPZP41TDU:-841395740) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L3632)):_

> ``` Markdown
> Here you can see that I have a selected row in a data grid (1). I want to scroll that 
> row to the top of the data grid (2).
> ```

This section should probably be in the passive voice

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2376 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRl1gkWuuop-pSvZll:-KLRmFNAJaMucpueiME7:1529717848) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2376)):_
<details><summary>

<i>Previously, jameshale (James Hale) wrote…</i></summary>



> Can I just re-edit the raw .md file that is linked to the pull request to do this stuff or do I need to do something else?
> </details>
> Good question... yes I believe that will work

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by jameshale** [comment]
_[Documentation/guides/LiveCode Data Grid.md, line 2376 [r1]](https://reviewable.io:443/reviews/livecode/livecode-ide/1251#-KLRl1gkWuuop-pSvZll:-KLRmeOa0ITZdvaOBgL_:485496232) ([raw file](https://github.com/livecode/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/LiveCode Data Grid.md#L2376)):_
<details><summary>

<i>Previously, livecodeali (Ali Lloyd) wrote…</i></summary>



> Good question... yes I believe that will work
> </details>
> ok. will go through this tomorrow (1:30 AM here)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/livecode/livecode-ide/1251)_

**Comment by livecodeali** [comment]
@jameshale Thank you so much for all your work on this! Aside from all the minor issues I've mentioned (many of which were already present), the only other thing I noticed is that the image
https://github.com/jameshale/livecode-ide/blob/d616e7b6c5e0bda289c4b871bfc5b687de65d464/Documentation/guides/images/datagrid-table-inspector-text.png
seems to have two random strips of transparency in it.

**Comment by jameshale** [comment]
Oh yeah.
I noticed that when I viewed it in the markdown but when I viewed raw it looked fine.
I will redo it.
Although not sure how I add the fixed version.

James

**Comment by livecodeali** [comment]
If you go to the appropriate location on the branch that this pull request is coming from (i.e.  [here](https://github.com/jameshale/livecode-ide/tree/community-docs/Documentation/guides/images)) and use the `Upload Files` button, as long as the image you upload has the same name as the older image, when you commit it will replace the old version and update the pull request automatically.

Now go to sleep! 💤

**Comment by jameshale** [comment]
Hi Ali,

Well I have updated the Guide and fixed the corrupted image.

Unfortunately I was not able to simply edit the guide using the web interface. Well I could edit it, it just choked when I tried to accept the changes.

I have instead updated the two files in my fork.

I see on the interface I am able to create a pull request for these commits, but I do not know if that is what I should do.

If i create a pull request will it not supersede the existing one?

Are you able to simply grab the two files? 

James

P.S. The changes to the guide consist of all your suggestions except for the internal link syntax.
In both my markdown editors (BBedit and MultiMarkdown Composer) your syntax was not recognised.
I have thus left the internal links in the form [heading text][]

**Comment by livecodeali** [comment]
@jameshale Thank you very much - the changes you made were committed to the same branch, so the commit was automatically added to this pull request.

**Comment by jameshale** [comment]
Oh, cool.

Clear as mud :-)

James

**Comment by livecodeali** [comment]
@jameshale Can you change the `>**Note:**`s and `>**Important:**`s to `>*Note:*`s and `>*Important:*`s please? That's how they are formatted elsewhere.

Otherwise, this is good to go!

**Comment by jameshale** [comment]
@livecodeali No they are not. 
Everywhere (I used LC8.1 feature of creating a pdf of all guides and did a search.) I have checked they are ALL  **BOLD**, that is they have 2 asterisks around them. (Exception is the unrevised data grid guide in current release). I have also checked the raw markdown files to check they reflect this. They do.

A single asterisk would make them _italic_

**Comment by livecodeali** [comment]
@jameshale Hmm, ok - looks like we have an inconsistency between the dictionary and guides there then. Thanks for checking.

@livecode-vulcan review ok 2223841

**Comment by livecodeali** [comment]
@jameshale Here is a gist showing the internal links working.

https://gist.github.com/livecodeali/596e515fa75d1764c41a3b98933301da

I used 

```
[click this to go to another subheading](#another-subheading)
```

**Comment by jameshale** [comment]
What is a gist?

Are you telling me these files are not really markdown?

James

**Comment by livecodeali** [comment]
A gist is just a text file, basically - but the crucial point here (which I probably should have made explicit, sorry) is that there are many flavours of markdown and the one we use in the dictionary / guides is GitHub flavoured markdown, as is the interpretation of markdown by gists.

**Comment by jameshale** [comment]
Ok, so is there a syntax guide to this flavor of markdown?
I realise now that the style of internal link I have been using is a multmarkdown extension.
However, when I look at syntax guides for just markdown I don't see the syntax you are putting forward (well if I am I am not recognizing it 😊.

**Comment by jameshale** [comment]
How's this.
Heading ->. ##word1 word2 word3##
`Link-> [nice text to display](#word1-word2-word3)`

(Needed to not let the link get processed by github, hence the inline code appearance)

**Comment by livecodeali** [comment]
I tend to use this:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Although I note that doesn't have that specific form there. I think what you have written is how it works, but I don't know where it is documented. I found it out by clicking the link next to a heading a seeing what the url said.

**Comment by jameshale** [comment]
Ok, I will reformat the internal links and resubmit.
Shouldn't take too long.

**Comment by jameshale** [comment]
@livecodeali Links have been reformatted but I still do not see them working.
Let's let it roll and see what comes out.

**Comment by livecodeali** [comment]
No, not working here either - It seems the rule is 

Heading ->. ##"Capitalised Words With P'unct'uation"?

```
Link-> [nice text to display](#capitalised-words-with-punctuation)
```

**Comment by jameshale** [comment]
yes that works.😊
(almost like pulling teeth insn't it?)

**Comment by livecodeali** [comment]
Hehe, indeed. Thank you! I will merge this now.

**Pull request merged**
