### PR TITLE
Merge develop 8.1 03.02.17

### PR DESCRIPTION
**Pull request by livecodeali**
Conflict in revstandalonesettings.8.rev

Resolved by keeping the develop version, and re-implementing the fix described in https://github.com/livecode/livecode-ide/pull/1526

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 0c8547f

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 0c8547f6e0a9e7917b3ae26e0ab09a8a4fa2dae3

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 52a07c1

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 52a07c1e88f8048cd1096b544cfa4ef7845aff04

**Pull request merged**
