### PR TITLE
[[ Bug 15745 ]] Ensure PI doesn't appear off screen

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by runrevben** [comment]
This was a feature that we disabled. I think there was a revIDEEnsureOnscreen function that checked where the use last put it as well as whether it was on screen. I think we wanted to refine the palettes before working on the placement. Is this fix redundant if we reenable that feature?

**Comment by livecodeali** [comment]
Sort of, although this one tries to place the PI to the left of the stack if it can't put it at the right, so slightly different

**Comment by livecodeali** [comment]
That's what revInternal__ConstrainStack does, doesn't it? Ensure on screen?

**Comment by runrevben** [comment]
Yeah I think so. The revIDEEnsureOnscreen looks at prefs and stores positions and sizes on close. I think it needed refinement. If you're happy with the fix as it is, I can review ok.

**Comment by livecodeali** [comment]
I don't see a revIDEEnsureOnscreen, but it's probably a good idea to ensure arbitrary palettes are onscreen after checking the prefs.

**Comment by runrevben** [comment]
@livecode-vulcan review ok 4b826d2

**Comment by livecode-vulcan** [comment]
💙 review by @runrevben ok 4b826d23572f1e2d8868860032c3a78d9121692a

**Pull request merged**
