### PR TITLE
Feature script editor variable filter

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 8f041ef

**Comment by peter-b** [comment]
Do you think there's an opportunity here to have a generic "filter box behaviour" script?  Maybe it would be possible to set a custom property on the field with the placeholder text to be used.

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 8f041ef1cbe5ea31e5976a248e16fbe9f1bb8cd3

**Comment by peter-b** [comment]
At the moment it seems like there are two behaivours with almost identical contents...

**Comment by livecodeali** [comment]
Probably, yes

**Comment by techstrategies** [comment]
I was going to merge the filter behaviour with the one from the handler list, happy to make the modification.

**Comment by peter-b** [comment]
@techstrategies That would be great. :grinning: It's really nice to avoid having the same code in two places because if there's a bug you only have to fix it once!

**Comment by techstrategies** [comment]
@peter-b I was thinking that at the time... will commit that shortly.

**Comment by techstrategies** [comment]
Pull request submitted https://github.com/livecode/livecode-ide/pull/493

**Comment by livecodeali** [comment]
Great, thanks - I'll pull that into this one.

**Comment by livecodeali** [comment]
@livecode-vulcan review ok 4c9f7de

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok 4c9f7de17e84ef3ac08f81c657b8c418d30f32ed

**Comment by mwieder** [comment]
Cool. I was just starting to work on this with an eye to submitting a pull request, but I see that the work is already underway.

**Comment by techstrategies** [comment]
@mwieder I hope you hadn't spent much time on it yet!  The lack of filtering on variables was annoying me for a while, and I knew you were wanting it as well. :smiley:

**Comment by mwieder** [comment]
No problem at all. I was going to add separate tabs, but the checkboxes do the trick nicely.

**Pull request merged**
