### PR TITLE
[[ Bug 16079 ]] Activate breakpoints before preOpenStack handlers are called

### PR DESCRIPTION
**Pull request by techstrategies**

### CODE REVIEW

**Comment by livecodefraser** [comment]
Thanks!

@livecode-vulcan review okay 4f3b670

**Comment by livecode-vulcan** [comment]
💙 review by @livecodefraser ok 4f3b67088c25e85a6b96c530c66db44683b4e770

**Comment by livecodefraser** [comment]
@runrevmark is there a reason this was done in openStack previously?

**Comment by livecodesebastien** [comment]
@techstrategies: In the next times you propose a fix (thanks again for your help!), can you simply delete the code that you remove, instead of commenting it? That leaves the source a bit cleaner, especially if the previous code was wrong :) Thank you for the patch anyway!

**Comment by techstrategies** [comment]
@livecodesebastien no worries, will do!

**Pull request merged**
