### PR TITLE
[[ Docs ]] Add docs preview facility when gRevDevelopment is true

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali I thought you said you weren't going to do any work this weekend!? :neutral_face:

**Comment by livecodeali** [comment]
That would be an ecumenical matter.

But seriously, this stuff was pretty much resting on my laptop, waiting to be rebased, honest.

**Comment by mwieder** [comment]
LOL. "it rebased itself, honest..."

**Comment by peter-b** [comment]
@livecodeali Is it feasible to use this docs preview facility to provide a "View Documentation" button in the extension builder palette?  This would be a really nice feature for extension authors.

**Comment by livecodeali** [comment]
Yes, the ultimate intention is that such a button will be available at all times in various contexts where it applies. This PR is more just about me being able to preview IDE docs while I write them. (Sorry, I should have said as much in the comments)

**Pull request closed without merging**
