### PR TITLE
[[ Bug 17233 ]] Allow 'no objects selected' state of PI

### PR DESCRIPTION
**Pull request by livecodeali**

### CODE REVIEW

**Comment by peter-b** [comment]
@livecodeali Looks good -- but it would be even better with a "this space intentionally left blank" label. :wink:

**Comment by livecodeali** [comment]
screen shot 2016-03-29 at 10 09 35

**Comment by peter-b** [comment]
@livecodeali That looks really good :sunglasses: 

@livecode-vulcan review ok c498e6d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok c498e6da3fc6fa90e1462d263798a15fb2c02b30

**Pull request merged**
