### PR TITLE
[[ Bug 19504 ]] Allow tab in text property of PI

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
You are abusing the `options` field a bit here, although I'm not sure there's another option beyond having a `textwithtabs` editor or something. Or declaring the editors as `textwithtabs` and adding a hack to the group behavior like with styledtext. Hmmm

**Comment by montegoulding** [comment]
Hehe... well what other kind of options would we want for a text field?

**Comment by livecodeali** [comment]
@livecode-vulcan review ok e39d852

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok e39d852896b389be3aa8ea8bf5a94b4ad2717c93

**Pull request merged**
