### PR TITLE
Load "messageauthentication" lib on startup

### PR DESCRIPTION
**Pull request by livecodepanos**

### CODE REVIEW

**Comment by montegoulding** [comment]
@livecodepanos I have a patch for this here https://github.com/livecode/livecode-ide/pull/1589 but it also includes the AWS S3 library which is still waiting for someone to review it. https://github.com/livecode/livecode-private/pull/151

**Comment by montegoulding** [comment]
@livecode-vulcan review ok 18c1193

**Comment by livecode-vulcan** [comment]
💙 review by @montegoulding ok 18c1193c6b7274c01ac3f297499900e87005cdec

**Comment by livecodepanos** [comment]
Sorry @montegoulding I missed that #1589 addresses this issue. I am closing this PR then, and I'll merge the other related PRs into `develop`

**Pull request closed without merging**
