### PR TITLE
[[ SB Inclusions ]] Reinstate radio buttons on first card

### PR DESCRIPTION
**Pull request by livecodeali**
The radio buttons control the enabled or otherwise of the
new Inclusions pane button.

### CODE REVIEW

**Comment by livecodeali** [comment]
Added to the General card script

```
   if tStandaloneSettingsA["inclusions"] is "select" then
      set the hilitedButtonName of group "inclusions" of me to "select"
      enable button "inclusions" of group "cards" of this card of me
   else
      set the hilitedButtonName of group "inclusions" of me to "search"
      disable button "inclusions" of group "cards" of this card of me
   end if
```

**Comment by livecodeali** [comment]
screen shot 2016-05-17 at 11 16 55

**Comment by peter-b** [comment]
@livecode-vulcan review ok 436285e

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 436285e218dd6f7bd72b6ddc887f4651f831c446

**Pull request merged**
