### PR TITLE
[[ Bug 16780 ]] Make docs cache per-version and per-edition

### PR DESCRIPTION
**Pull request by livecodeali**
Also clean up old docs cache.

### CODE REVIEW

**Comment by peter-b** [comment]
@livecode-vulcan review ok 20b581d

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 20b581d900547b7efe089c333aac78188a776381

**Comment by peter-b** [comment]
@livecode-vulcan review ok 0968e12

**Comment by livecode-vulcan** [comment]
💙 review by @peter-b ok 0968e126d14ea2892d4016fdf082f19655778a5c

**Pull request merged**
