### PR TITLE
[[ Bug ]] Fix selection update issues

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodeali** [comment]
What's going on here then?

**Comment by montegoulding** [comment]
Ah well there's two things:
- for some reason I added a check to see if selectionUpdateRequest was called with a target of the script field (not necessary and interferes with action based edits from the menu etc)
- selectionUpdateRequest is called in textReplace now so no need to also call it after these actions

**Comment by montegoulding** [comment]
Sorry I can amend the commit msg with ^ if you like

**Comment by livecodeali** [comment]
Yeah, I think that would be good. Looks fine though!

**Comment by montegoulding** [comment]
done

**Comment by livecodeali** [comment]
@livecode-vulcan review ok ef926dd

**Comment by livecode-vulcan** [comment]
💙 review by @livecodeali ok ef926dda29a4d540958be6cf43663e36102a63cc

**Pull request merged**
