### PR TITLE
[[ Bug ]] Fix inspector lock recursion

### PR DESCRIPTION
**Pull request by montegoulding**

### CODE REVIEW

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok c4cc822

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok c4cc822566e6f0d9aaf674d32904b15575118e88

**Comment by livecodepanos** [comment]
@livecode-vulcan review ok 79b0256

**Comment by livecode-vulcan** [comment]
💙 review by @livecodepanos ok 79b0256109e3d54360e64db90ac867a928a85f1d

**Pull request merged**
